---
sidebar: sidebar
permalink: configure-data-migrator.html
keywords: configure, log, in, project, create, app admin
summary: "Log in as an App Admin (administrator) using the default credentials and update your username and password."
---
= Configure NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
After you install NetApp Data Migrator, you need to log in as an App Admin (administrator) using the default username and password.

[[log-in]]
== Log in to NetApp Data Migrator
Log in to NetApp Data Migrator, then change your login credentials and create your first project.

.Steps

. Open a web browser and navigate to NetApp Data Migrator:
+
`https://<private_IP_address>/`.
. On the *Welcome* page, enter the default username in *Username/Email* .
. Enter the default password in *Password* .
. Select *Login*. 
+
The *Reset Password* page opens.
. Enter a new password that meets the following security requirements:
* Includes at least 8 characters
* Includes at least one uppercase letter
* Includes at least one lowercase letter
* Includes at least one number
* Includes at least one special character
. Select *Reset Password*. The *Your Details* page opens.
. Enter your *First Name*, *Last Name*, and *Email* address.
. Select *Proceed*. The *Create a New Project* page opens.
. Select *Create Project*, then enter the following details:
* *Project Name*: Enter a descriptive name for your project.
* *Project Description (Optional)*: You can provide additional details about your project.
. Select *Create*.
+
The new project appears in the notification bar at the top of the NetApp Data Migrator control plane.

== Log out of NetApp Data Migrator

After you log out of NetApp Data Migrator, you need to use your newly created credentials (email and password) the next time you log in.

.Steps

. Select the *User* icon (next to *Settings*).
. Select *Logout*. The *Welcome* page opens.
. In *Email* and *Password*, enter the email address and password that you registered when you <<log-in,logged in>>.
. Select *Login*.

.What's next?

After learning about configuring NetApp Data Migrator, you can link:manage-projects.html[use NetApp Data Migrator].