---
sidebar: sidebar
permalink: configure-bulk-cutover.html
keywords: 
summary: 
---
= Configure Bulk Cutover in NDM
:icons: font
:imagesdir: ./media/

[.lead]
Use Bulk Cutover in NetApp Data Migrator (NDM) to perform the final sync between your source and destination systems. When baseline migrations are complete and incremental syncs are running, you can merge multiple paths into one cutover job.

== Start a Cutover Job

.Follow these steps to start a cutover job:

. Log in to NDM.
. Select *Storage Servers* in the left navigation pane.
. From the dropdown menu, select *File Servers*.
. Select the name of the file server for which you want to create a Cutover Job.
. Select *Bulk Cutover.*

Next, on the *Select Path* page:

. Select the checkbox next to *Source Path.*
. Select the checkbox next to the source path (confirming the cutover job).
. Select *Proceed.*
. You can select a job even if a *Bulk Migrate* job is running in parallel. Select the *checkbox* next to a job name to confirm that you are starting a *Bulk Cutover* job.
. Select *Submit* to start your *Bulk Cutover* job and a notification message appears, confirming that a *Cutover job has been created*.
. You can select the *View Job Listing* link next to this message to open the *Job List* page where your new job is listed.

== Approve a Bulk Cutover

.Follow these steps to approve a cutover job:

. On the *Jobs* page, select the *Job Run List* tab.
. Select the action menu next to your Cutover job.
. Select *Review,* then a Cutover Confirmation pop-up box appears.
. Select the *Download CoC Report* link to download. Review this report to verify if the cutover was successful and all data has successfully migrated from source to destination.
. Select the checkbox next to *I have reviewed and verified the COC document and all other essential information.*
. If you are satisfied with the information in the COC report, select *Confirm* to approve the *Bulk Cutover* and the *Status* changes to *Complete.* 
