---
sidebar: sidebar
permalink: create-azure-control-plane-worker-vm.html
keywords: azure, control plane, worker vm, nfs migration, smb migration
summary: "After installing Azure CLI, create the control plane and Linux and Windows worker VMs for NFS and SMB migrations."
---
= Use Azure to create the control plane and worker VMs for NDM
:icons: font
:imagesdir: ./media/

[.lead]
After installing Azure using the CLI, create the control plane and worker virtual machines (VMs) to access NDM. The worker VMs run on Linux or Windows and they perform the data migration. Linux supports the NFS protocol and Windows supports the SMB protocol. You can install multiple worker VMs based on your needs.

== Step 1: Create the control plane VM

To create the control plane VM, you need to use the previously imported control plane image. 

Learn how to link:https://learn.microsoft.com/en-us/azure/virtual-machines/capture-image-resource#portal-create-a-vm-from-a-legacy-managed-image[create a VM from a custom imported image^]. Use the following recommended settings:

* Image: Custom imported
* Size: 16 vCPU, 64 GB RAM
* License type: Other

== Step 2: Create the Linux worker VM 

Create the Linux worker VM for NFS migration using the previously imported worker image.

Learn how to link:https://learn.microsoft.com/en-us/azure/virtual-machines/capture-image-resource#portal-create-a-vm-from-a-legacy-managed-image[create a worker VM from a custom imported image^]. Use the following recommended settings:

* Image: Custom imported
* Size: 4 vCPU, 16GB RAM
* License type: Other

== Step 3: Add the Windows Worker Installer

Add the Windows Worker Installer for SMB migration.

.Steps
//. Download the Windows Worker Installer for Azure from the link:https://mysupport.netapp.com/site/[NetApp Support site^]. 
. Download the Windows Worker Installer for Azure from the preview link provided. 

. Learn how to link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/quick-create-portal[create a Windows VM^]. Use the following recommended settings:
+
** Image: Choose Windows Server 2022 
** Datacenter: Azure Edition - x64 Gen2
** Size: 16 vCPUs, 64 GB memory
** RDP port 3389 open 

. Move the Windows Worker Installer to the Windows VM
* Log in to the Windows worker VM using the Remote Desktop Protocol and copy the Windows Worker Installer to the Windows VM.
* Use Microsoft Windows App (Mac) or RDP (Windows) to create a remote session. 
+
Learn about link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/connect-rdp[RDP connections^].

. Depending on your configuration, select the MacOS or Windows tab.
+
[role="tabbed-block"]
====
.MacOS
--
Windows worker for MacOS:

.. Install the Microsoft Windows App on your local laptop.
.. link:https://learn.microsoft.com/en-us/windows-app/get-started-connect-devices-desktops-apps[RDP into the SMB Windows worker VM^].
.. link:https://learn.microsoft.com/en-us/windows-app/device-audio-folder-redirection-teams?tabs=macos#folder-redirection[Mount the local folder which contains the Windows Worker Installer^].
.. Locate the folder you mounted to the Windows worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM.
--
.Windows
--
Windows worker for Windows:

.. Launch a Remote Desktop Connection.
.. link:https://cat.pdx.edu/platforms/windows/remote-access/file-sharing-rdp-from-windows/[RDP into the SMB Windows worker VM and mount the local folder containing the Windows Worker Installer^]. 
.. Locate the folder you mounted to the Windows worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM .
--
====

== Step 4: Connect to the control plane VM

Connect to the control plane to validate if NDM is active.

.Steps
. Install Azure CLI. Refer to the Azure CLI Download instructions.
. Use SSH to connect to your control plane server. If your server does not have a public IP address, follow the steps in the link:https://learn.microsoft.com/en-us/azure/bastion/quickstart-host-portal[Azure Bastion documentation^] to configure SSH access.
. Switch the user to `datamigrator`:
+
[source,cli]
----
sudo su - datamigrator
----
. Check the status of boot service and logs:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
. Optionally, check the boot service logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
. If you see "Datamigrator Application Setup Complete" in the logs, it indicates the setup is complete.
. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----

. You can now access NDM using RDP with the Windows VM created for NDM access and the control plane private IP address.
+
The default credentials for the NDM UI are:
+
* URL: `https://<control-plane-private-ip>/`
* Username: admin@datamigrator.local
* Password: Welcome@123

. Depending on your migration, select the NFS or SMB tab.
+
[role="tabbed-block"]
====
.NFS
--
Associate the Linux worker with the control plane VM:

.. Log in to the Windows VM using RDP to access NDM.
* Use Microsoft Windows App (Mac) or Remote Desktop Connection (Windows) to create an RDP session.
* Learn about link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/connect-rdp[RDP connections^].
.. Retrieve the private IP address from the newly created control plane VM in Azure.
.. Open any browser and navigate to the NDM UI using the following credentials: 
* IP address: `https://<control_plane_IP_address>/`
* Username: admin@datamigrator.local
* Password: Welcome@123
.. Reset the password.
.. Add the new user details and email ID.
.. Create a new project by providing a name and an optional description.
.. Select *View Instructions to Setup Worker* and copy the instructions. 
.. To associate the Linux worker with the CP, use SSH to connect to your worker server. If your server does not have a public IP address, you can use Bastion to configure SSH access. 
* Log in as root user:
+
[source,cli]
----
sudo su -
----
* Paste the instructions copied from *View Instructions to Setup Worker* to register the worker VM.
* Verify the status of the worker:
+
[source,cli]
----
systemctl status datamigrator-worker.service
----
* Check the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
* Navigate to the NDM UI and verify that the worker is registered.
--

.SMB
--
Add the Active Directory to the Windows VM. Then, associate the Windows worker with the control plane VM:

.. Select *Settings* > *Network & Internet* > *Ethernet*.
.. Select *Network and Sharing Center*.
.. In the pop-up window, select *Ethernet*.
.. In the pop-up window, select *Properties*.
.. In the pop-up window, double-click on *Internet Protocol Version 4 (TCP/IPv4)*.
.. Select *Use the following DNS server addresses*, then enter the Active Directory server IP in *Preferred DNS server*.
.. Select OK.
.. Run the Windows Worker Installer that you copied to the Windows Worker Server.
.. Enter the following details when prompted. You can get these details from the NDM UI by selecting *Home > View Instructions to Setup Worker*:
* Worker ID
* Worker secret
* Project ID
* Control plane Private IP address

.. Disable Windows defender:
+
[source,cli]
----
PS C:\Windows\system32> Set-MpPreference -DisableRealtimeMonitoring $true
----
+
[source,cli]
----
PS C:\Windows\system32> Add-MpPreference -ExclusionPath "C:\datamigrator\mnt"
----

.. Disable Windows update in Windows services.

.. When installation completes, the worker service starts automatically and you can locate the logs in `C:\datamigrator\logs`.
.. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name>" -Wait
----
.. Open the command prompt (cmd) as Administrator and run the following commands to manage the Service:
* Start the service:
+
[source,cli]
----
net start DatamigratorWorker
----
* Stop the service:
+
[source,cli]
----
net stop DatamigratorWorker
----
* Restart the service:
+
[source,cli]
----
net stop DatamigratorWorker && start DatamigratorWorker
----
--
====

You should consider the following when installing NDM using Azure:

* *SAS URLs are time-limited*: Start your copy operation as soon as possible—typically within 7 days.

* *Validate copy is complete*: Do not use a partially copied VHD for deployments.

* *Checksum validation is recommended*: This ensures your VHD’s integrity matches the original source.

* *Repeat the full process* for each VHD (Control Plane and Worker).

The following tables describes the placeholder references:

|===
| Placeholder | Description
| <YOUR_STORAGE_ACCOUNT>	 | Destination storage account name
| <YOUR_RESOURCE_GROUP>	 | Resource group name
| <YOUR_AZURE_REGION> | Azure region (e.g., East us)
| YOUR_CONTAINER_NAME| Container for VHD storage
| YOUR_STORAGE_ACCOUNT_KEY| Storage account access key
| <YOUR_SUBSCRIPTION_ID>| Azure subscription ID
| <YOUR_TENANT_ID>	| Azure tenant ID
| <YOUR_IMAGE_NAME>	| Name for the managed image
| <PROVIDED_SAS_URL>| The SAS URL provided by our team
| <VHD_FILE_NAME>	| VHD file name (without .vhd extension)
| <SHA_FILE_NAME>	| Checksum file name (without .sha256 extension)
|===

.What's next?

link:configure-ndm.html[Learn about configuring NDM]

// 2026 FEB 25, Preview + 3 release
// 9 OCT 2025, commented out lines with the NSS link and replaced them with "preview link provided" - temporary measure for preview only.