---
sidebar: sidebar
permalink: create-aws-control-plane-worker-vm.html
keywords: 
summary: 
---
= Use AWS to create the control plane and worker VMs for NDM
:icons: font
:imagesdir: ./media/

[.lead]
After installing AWS using the CLI, create the control plane and worker VMs to access NDM.

== Step 1: Create the Windows VM

Create a Windows VM to access NDM using the Remote Desktop Protocol.

Learn how to link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/launch-marketplace-console.html[create the Windows VM^]. Use the following recommended settings:

* Image: Microsoft Windows 2022 Datacenter Base 
* Architecture: 64-bit (x86), Ami: ami-0fc8a85749a35ce56 
* Size: 16 vCPU, 64 GB memory
* RDP port 3389 open

== Step 2: Create the control plane VM

To create the control pane VM, use the previously imported control plane image. 

Learn how to link:https://repost.aws/knowledge-center/launch-instance-custom-ami[create a VM from a custom imported image^]. Use the following recommended settings:

* Image: Custom imported
* Size: 16 vCPU, 64 GB RAM
* License type: Other

== Step 3 (a): Create the Linux worker VM 

Create the Linux worker VM for NFS migration using the previously imported worker image.

Learn how to link:https://repost.aws/knowledge-center/launch-instance-custom-ami[create a worker VM from a custom imported image^]. Use the following recommended settings:

* Image: Custom imported
* Size: 4 vCPU, 16GB RAM
* License type: Other

== Step 3 (b): Add the Windows Worker Installer

Add the Windows Worker Installer for SMB migration.

.Steps
. Download the Windows Worker Installer for AWS from the preview link provided. 

. Learn how to link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/launch-instances-from-launch-template.html[create a Windows VM^]. Use the following recommended settings:
+
** Image: Choose Windows Server 2022 Base 
** Architecture: 64-bit (x86), Ami: ami-0fc8a85749a35ce56 
** Size: 16 vCPUs, 64 GB memory
** RDP port 3389 open 

. Move the Windows Worker Installer to the Windows VM
.. Log in to the Windows worker VM using the Remote Desktop Protocol and copy the Windows Worker Installer to the Windows VM.
.. Use Microsoft Windows App (Mac) or RDP (Windows) to create a remote session. 
+
Learn about link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-rdp.html[RDP connections^].


. Depending on your configuration, select the MacOS or Windows tab.
+
[role="tabbed-block"]
====
.MacOS
--
Windows worker for MacOS.

.. Install the Microsoft Windows App on your local laptop.
.. link:https://learn.microsoft.com/en-us/windows-app/get-started-connect-devices-desktops-apps[RDP into the SMB Windows worker VM^].
.. link:https://learn.microsoft.com/en-us/windows-app/device-audio-folder-redirection-teams?tabs=macos#folder-redirection[Mount the local folder which contains the Windows Worker Installer^].
.. Locate the folder you mounted to the Windows worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM.
--
.Windows
--
Windows worker for Windows:

.. Launch a Remote Desktop Connection.
.. link:https://cat.pdx.edu/platforms/windows/remote-access/file-sharing-rdp-from-windows/[RDP into the SMB Windows worker VM and mount the local folder containing the Windows Worker Installer^]. 
.. Locate the folder you mounted to the Windows worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM .
--
====

== Step 4: Connect to the control plane VM

Connect to the control plane to validate if NDM is active.

.Steps
. Install the AWS CLI. Refer to the AWS CLI Download instructions.
. Use SSH to connect to your control plane server. If your server does not have a public IP address, follow the steps in the link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-with-ec2-instance-connect-endpoint.html[AWS documentation^] to configure SSH access. 
. Switch the user to `datamigrator`:
+
[source,cli]
----
sudo su - datamigrator
----
. Check the status of the boot service and logs:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
Optionally, check the boot service logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
. If you see "Datamigrator Application Setup Complete" in the logs, it indicates the setup is complete.
. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----

. You can now access NDM using RDP with the Windows VM created for NDM access and the control plane private IP address.
+
The default credentials for the NDM UI are:
+
* URL: `https://<control-plane-private-ip>/`
* Username: admin@datamigrator.local
* Password: Welcome@123

. Depending on your migration, select the NFS or SMB tab.
+
[role="tabbed-block"]
====
.NFS
--
Associate the Linux worker with the control plane VM.

.. Log in to the Windows VM using RDP to access NDM.
* Use Microsoft Windows App (Mac) or Remote Desktop Connection (Windows) to create an RDP session.
* Learn about link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-rdp.html[RDP connections^].
.. Retrieve the private IP address from the newly created control plane VM in AWS.
.. Open any browser and navigate to the NDM UI using the following credentials: 
* IP address: `https://<control_plane_IP_address>/`
* Username: admin@datamigrator.local
* Password: Welcome@123
.. Reset the password.
.. Add new user details and email ID.
.. Create a new project by providing a name and an optional description.
.. Select *View Instructions to Setup Worker* and copy the instructions. 
.. To associate the Linux worker with the CP,
Use SSH to connect to your worker server. If your server does not have a public IP address, you can use Bastion to configure SSH access. 
* Log in as root user:
+
[source,cli]
----
sudo su -
----
* Paste the instructions copied from *View Instructions to Setup Worker* to register the worker VM.
* Verify the status of the worker:
[source,cli]
----
systemctl status datamigrator-worker.service
----
* Check the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
* Navigate to the NDM UI and verify that the worker is registered.
--

.SMB
--
Associate the Windows worker with the control plane VM.

.. Run the Windows Worker Installer that you copied to the Windows Worker Server.
.. Enter the following details when prompted. You can get these details from the NDM UI under *Home > View Instructions to Setup Worker:*
* Worker ID
* Worker secret
* Project ID
* Control plane Private IP address

.. Disable Windows defender:
+
[source,cli]
----
PS C:\Windows\system32> Set-MpPreference -DisableRealtimeMonitoring $true
----
+
[source,cli]
----
PS C:\Windows\system32> Add-MpPreference -ExclusionPath "C:\datamigrator\mnt"
----

.. Disable Windows update in Windows services.

.. When installation completes, the worker service starts automatically and you can then locate the Logs at:
+
[source,cli]
----
C:\datamigrator\logs
----
.. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name> -Wait
----
.. Open the command prompt (cmd) as Administrator and run the following commands to manage the Service:
* Start the service:
+
[source,cli]
----
net start DatamigratorWorker
----
* Stop the service:
+
[source,cli]
----
net stop DatamigratorWorker
----
* Restart the service:
+
[source,cli]
----
net stop DatamigratorWorker && start DatamigratorWorker
----
--
====

You should consider the following when installing NDM using AWS:

.What's next?

link:configure-ndm.html[Learn about configuring NDM]
