---
sidebar: sidebar
permalink: create-control-plane-vm.html
keywords: google cloud, installation, control plane, worker vm, iam roles
summary: "Create VM instances on Google Cloud by enabling required APIs, preparing storage, configuring IAM roles, and deploying control plane and worker VMs."
---
= Create the control plane VM to access NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
Create the control plane VM using AWS, Azure, or Google Cloud service or OVA templates to access NetApp Data Migrator.

.About this task
You create control plane workers VM for NFS and SMB using the deployed control plane image. A Linux worker VM supports NFS migrations and a Windows worker VM supports SMB migrations. You can create multiple worker VMs based on your needs.

.Steps
. Using the deployed control plane image, create a control plane VM with the following recommended configuration:
+
|===
| Description | Recommended setting

| VM configuration
a|* Image: Custom imported image for the control plane
* Network interface card type: gVNIC
* Size: 8 vCPU, 64 GB RAM
* Storage: 200 GB
| Hyper scaler
a|* AWS: r7i.2xlarge instance
* Azure VM size : Standard_E8ds_v5 
* Google Cloud machine type : c3-highmem-8  
|===

. Create the Linux worker VM to support NFS migration with the following recommended configuration:
+
|===
| Description | Recommended setting

| VM configuration
a|* Image: Custom imported image for the control plane
* Network interface card type: gVNIC
* Size: 4 vCPU, 16 GB RAM
* Storage: 100 GB
| Hyper scaler
a|* AWS: r7i.2xlarge
* Azure VM size : Standard_E8ds_v5 
* Google Cloud machine type : c3-highmem-8  
|===

. Create  a Windows worker VM to support SMB migrations:
.. Download Windows Worker Installer using the link provided.
.. Create a Windows VM with the following recommended configuration settings:  
+
* Image: Windows Server 2022 Base 
* Architecture: 64bit 
* Size: 16 vCPU, 64 GB RAM 
* Network interface card type: gVNIC 
* Ensure Remote Desktop Protocol (RDP) (3389) is open 
. Create a remote working session using RDP.
+
Learn about link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/connect-rdp.html[RDP connections^].
. Copy and run the Windows Worker Installer on the control plane VM. 

.What's next?

Choose one of the following options:

* Optionally, learn about link:validate-control-plane-vm.html[validating the control plane VM]
* Learn about link:access-data-migrator-ui.html[accessing the NetApp Data Migrator UI and connecting to the control plane and workers]

// 2026 FEB 25, Preview + 3 release
// 2025 DEC 1, OTHERDOC-168
// 9 OCT 2025, commented out lines with the NSS link and replaced them with "preview link provided" - temporary measure for preview only.
