---
sidebar: sidebar
permalink: create-windows-vm-on-google-cloud.html
keywords: google cloud, installation, control plane, worker vm, iam roles
summary: "Create VM instances on Google Cloud by enabling required APIs, preparing storage, configuring IAM roles, and deploying control plane and worker VMs."
---
= Create Windows VM on Google Cloud for NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
---
Create Windows VM instances on Google Cloud for NetApp Data Migrator using the Remote Desktop Protocol (RDP).

.Steps

. Create the control plane VM using the imported control plane image.
+
Learn how to link:https://cloud.google.com/compute/docs/instances/create-vm-from-custom-image[create a VM from a custom imported image^]. Use the following recommended settings:
+
* Size: 16 vCPU, 64 GB RAM
* Image: Custom imported image for the control plane.

. For NFS migration, create the Linux worker using the imported control plane image. 
+
Learn how to link:https://cloud.google.com/compute/docs/instances/create-vm-from-custom-image[create a VM from a custom imported image^]. Use the following recommended settings:
+
* Size: 4 vCPU, 16 GB RAM
* Image: Custom imported image for the control plane.

. For SMB migration, add the Windows Worker Installer:
//.. Download the Windows Worker Installer for Google Cloud Platform from the link:https://mysupport.netapp.com/site/[NetApp Support site^]. 
.. Download the Windows Worker Installer for Google Cloud Platform from the preview link provided. 
.. Learn how to link:https://cloud.google.com/compute/docs/create-windows-server-vm-instance[create a Windows Server VM instance^]. Use the following recommended settings for the Windows worker VM:
+
* Image: Windows Server 2022 Datacenter
* Size: 16 vCPU, 64 GB RAM.
* RDP port 3389 open

.. Move the Windows Worker Installer to the Windows VM:

... Log in to the Windows worker VM using RDP and copy the Windows Worker Installer to the Windows VM.
... Use Microsoft Windows App (Mac) or RDP (Windows) to create an RDP session.
... link:https://cloud.google.com/compute/docs/instances/connecting-to-windows[Connect to the Windows VM using RDP^].

. Depending on your configuration, select the MacOS or Windows tab.
+
[role="tabbed-block"]
====
.MacOS
--
Windows worker for MacOS:

.. Install the Microsoft Windows App on your local laptop.
.. link:https://learn.microsoft.com/en-us/windows-app/get-started-connect-devices-desktops-apps[RDP into the SMB Windows worker VM^].
.. link:https://learn.microsoft.com/en-us/windows-app/device-audio-folder-redirection-teams?tabs=macos#folder-redirection[Mount the local folder which contains the Windows Worker Installer^].
.. Locate the folder you mounted to the Windows worker VM under `This PC` on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM.
--
.Windows
--
Windows worker for Windows:

.. Launch a Remote Desktop Connection.
.. link:https://cat.pdx.edu/platforms/windows/remote-access/file-sharing-rdp-from-windows/[RDP into the SMB Windows worker VM and mount the local folder containing the Windows Worker Installer^]. 
.. Locate the folder you mounted to the Windows worker VM under `This PC` on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM .
--
====

. Connect to the control plane VM:

.. Use SSH to connect to the control plane VM:
+
[source,cli]
----
gcloud compute ssh <control-plane-instance-name> --internal-ip --zone <zone-name>
----

.. Switch the user to datamigrator:
+
[source,cli]
----
sudo su - datamigrator
----
.. Check the status of boot service and logs:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
Optionally, check the boot service logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
.. If you see `Datamigrator Application Setup Complete` in the logs, this indicates the setup is complete.
.. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----
+
Access NetApp Data Migrator using RDP with the Windows VM you created for NetApp Data Migrator access and the control plane private IP address. Login in to the NetApp Data Migrator UI using the default username and password.

. Depending on your migration, select the NFS or SMB tab:
+
[role="tabbed-block"]
====
.NFS
--
Associate Linux worker with the control plane VM:

.. Log in to the Windows VM using RDP to access NetApp Data Migrator.
* Use Microsoft Windows App (Mac) or Remote Desktop Connection (Windows) to create an RDP session.
* link:https://cloud.google.com/compute/docs/instances/connecting-to-windows[Connect to the Windows VM using RDP^].
.. Retrieve the private IP address from the newly created control plane VM in GCP.
.. Open any browser and navigate to the NetApp Data Migrator UI using the control place IP address and the default username and password.
.. Reset the password.
.. Add the new user details and email ID.
.. Create a new project by providing a name and an optional description.
.. Select *View Instructions to Setup Worker* and copy the instructions. 
.. To associate the Linux worker with the CP, use SSH to connect to your worker server. If your server does not have a public IP address, you can use Bastion to configure SSH access. 
* Log in as root user:
+
[source,cli]
----
sudo su -
----
* Paste the instructions copied from *View Instructions to Setup Worker* to register the worker VM.
* Verify the status of the worker:
+
[source,cli]
----
systemctl status datamigrator-worker.service
----
* Check the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
* Navigate to the NetApp Data Migrator UI and verify that the worker is registered.
--

.SMB
--
Add the Active Directory to the Windows VM. Then, associate the Windows worker with the control plane VM:

.. Select *Settings* > *Network & Internet* > *Ethernet*.
.. Select *Network and Sharing Center*.
.. In the pop-up window, select *Ethernet*.
.. In the pop-up window, select *Properties*.
.. In the pop-up window, double-click on *Internet Protocol Version 4 (TCP/IPv4)*.
.. Select *Use the following DNS server addresses*, then enter the Active Directory server IP in *Preferred DNS server*.
.. Select OK.
.. Run the Windows Worker Installer that you copied to the Windows Worker Server.
.. Enter the following details when prompted. You can get these details from the NetApp Data Migrator UI by selecting *Home > View Instructions to Setup Worker*:
* Worker ID
+
NOTE: Use one worker ID per worker. Don't use the same worker ID to set up multiple workers.
* Worker secret
+
NOTE: Use one worker secret per worker. Don't use the same worker secret to set up multiple workers.
* Project ID
* Control plane Private IP address

.. Disable Windows defender:
+
[source,cli]
----
PS C:\Windows\system32> Set-MpPreference -DisableRealtimeMonitoring $true
----
+
[source,cli]
----
PS C:\Windows\system32> Add-MpPreference -ExclusionPath "C:\datamigrator\mnt"
----

.. Disable Windows update in Windows services.

.. When installation completes, the worker service starts automatically and you can locate the Logs in `C:\datamigrator\logs`.
.. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name>" -Wait
----
.. Open the command prompt (cmd) as Administrator and run the following commands to manage the Service:
* Start the service:
+
[source,cli]
----
net start DatamigratorWorker
----
Stop the service:
+
[source,cli]
----
net stop DatamigratorWorker
----
Restart the service:
+
[source,cli]
----
net stop DatamigratorWorker && start DatamigratorWorker
----
--
====

The following tables describes the placeholder references:

|===
| Placeholder | Description

| <PROJECT_ID>	 | Your GCP project ID
| <PROJECT_NUMBER>	 | Your GCP project number
| <GCS_BUCKET> | Your GCS bucket name
| <IMAGE_NAME>| VM image name (without extension)
| <IMAGE_IMPORT_NAME>| Unique name for the import task
| <REGION>| Your region. For example, US EAST 4.
|===


.Related information

* link:https://cloud.google.com/compute/docs/create-windows-server-vm-instance[Learn about creating Windows Server VM^]
* link:https://cloud.google.com/storage/docs/uploading-objects#uploading-an-object[Learn about uploading objects to GCS^]

.What's next?

link:configure-netapp-data-migrator.html[Learn about configuring NetApp Data Migrator]

// 2026 FEB 25, Preview + 3 release
// 2025 DEC 1, OTHERDOC-168
// 9 OCT 2025, commented out lines with the NSS link and replaced them with "preview link provided" - temporary measure for preview only.
