---
sidebar: sidebar
permalink: install-using-azure.html
keywords: 
summary: 
---
= Install NDM using Azure 
:icons: font
:imagesdir: ./media/

[.lead]
Use Azure to install NetApp Data Migrator (NDM).

.About this task

NDM has two main components that you need to install:

* The *control plane*, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

* *Workers* are virtual machines running on Linux, which supports the NFS protocol, or Windows, which supports the SMB protocol. You can install multiple workers based on your requirements:

** For shared message block (SMB) migration, use the Windows Worker Installer on a Windows VM.
** For NFS migration, use the Linux Worker.

.Before you begin

Before you can install the NDM control pane and worker, you must have:

* An active Azure subscription
* A Resource group set up in your desired region
* Sufficient disk space for data storage and VM deployment
* Azure command line interface (CLI) installed

If you do not have the Azure command line interface (CLI) already installed, proceed to Part 1 of the following instructions. Otherwise, proceed to Part 2 to learn how to install the NDM control plane and workers.  


== Part 1: Install Azure CLI and manage assets
This section explains how to deploy VMs in Azure using a virtual hard disk (VHD) shared by NetApp via a time-limited shared access signature (SAS) URL. You can then use the Azure CLI and portal to
copy these assets to your Azure storage, (optionally) validate integrity, and create deployable, managed images.

.Steps

. Select one of these links to learn how to install the Azure CLI on your operating system:
* link:https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&pivots=winget[Install on Windows]
* link:https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-macos[Install on macOS]
* link:https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux[Install on Linux]

. You can (optionally) authenticate and select your subscription using the following commands:
+
[source,cli]
----
az login --tenant <YOUR_TENANT_ID>
az account set --subscription <YOUR_SUBSCRIPTION_ID>
az account show
----
. Follow this link:https://learn.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-portal[link] to learn how to create storage and a container in your Azure account.
. Contact NetApp Support at [insert email/contact method] to request a time-limited SAS URL for the VHD and checksum file. The SAS URL provides temporary, secure access required for the deployment process described here.
. Copy control plane and worker VHDs:
* Retrieve the primary access key for your storage account:
+
[source,cli]
----
az storage account keys list \
  --resource-group <YOUR_RESOURCE_GROUP> \
  --account-name <YOUR_STORAGE_ACCOUNT> \
  --query "[0].value" -o tsv
----
* Copy the VHD file to your own Azure storage:
+
[source,cli]
----
az storage blob copy start \
  --source-uri "<PROVIDED_SAS_URL>" \
  --destination-blob "<VHD_FILE_NAME>.vhd" \
  --destination-container <YOUR_CONTAINER_NAME> \
  --account-name <YOUR_STORAGE_ACCOUNT> \
  --account-key <YOUR_STORAGE_ACCOUNT_KEY>
----
* Check to ensure that the copy completes successfully:
+
[source,cli]
----
az storage blob show \
  --account-name <YOUR_STORAGE_ACCOUNT> \
  --container-name <YOUR_CONTAINER_NAME> \
  --name "<VHD_FILE_NAME>.vhd" \
  --query "properties.copy.status" \
  -o tsv \
  --account-key <YOUR_STORAGE_ACCOUNT_KEY>
----
* Transfer the checksum file to the same container:
+
[source,cli]
----
az storage blob copy start \
  --source-uri "<PROVIDED_SAS_URL>" \
  --destination-blob "<SHA_FILE_NAME>.sha256" \
  --destination-container <YOUR_CONTAINER_NAME> \
  --account-name <YOUR_STORAGE_ACCOUNT> \
  --account-key <YOUR_STORAGE_ACCOUNT_KEY>
----
* To validate the checksum (optional), mount your blob storage to a Linux VM using link:https://learn.microsoft.com/en-us/azure/storage/blobs/blobfuse2-how-to-deploy?tabs=RHEL[Blobfuse2], then compute the checksum and for consistency, compare it to the one provided. Follow this link to link:https://linuxhostsupport.com/blog/how-to-verify-checksum-of-a-file-on-linux/[learn how to verify a checksum in Linux].
* Create a new managed Azure image from the copied VHD, then repeat for each VHD:
+
[source,cli]
----
az image create \
  --resource-group <YOUR_RESOURCE_GROUP> \
  --name <YOUR_IMAGE_NAME> \
  --source https://<YOUR_STORAGE_ACCOUNT>.blob.core.windows.net/<YOUR_CONTAINER_NAME>/<VHD_FILE_NAME>.vhd \
  --os-type linux \
  --location <YOUR_AZURE_REGION>
----

== Part 2: Create the control plane and worker VMs

*Step 1: Create the Windows VM*

You need to create a Windows VM to access NDM using the Remote Desktop Protocol. Follow this link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/quick-create-portal[link] to learn how to create a Windows VM, using these recommended settings:

* Image: Windows Server 2022
* Datacenter: Azure Edition - x64 Gen2
* Size: 8 vcpus, 32 GB memory
* RDP port 3389 open

*Step 2: Create the control plane VM*

To create the control pane VM, you need to use the previously imported control plane image. Follow this link:https://learn.microsoft.com/en-us/azure/virtual-machines/capture-image-resource#portal-create-a-vm-from-a-legacy-managed-image[link] to learn how to to create a VM from a custom imported image, using these recommended settings:

* Image: Custom imported
* Size: 8 vCPU, 32GB RAM
* License type: Other

*Step 3(a): Create the Linux worker VM for NFS migration* 

For NFS migration, you need to create the Linus worker VM using the previously imported worker image. Follow this link:https://learn.microsoft.com/en-us/azure/virtual-machines/capture-image-resource#portal-create-a-vm-from-a-legacy-managed-image[link] to learn how to create a worker VM from a custom imported image, using these recommended settings:

* Image: Custom imported
* Size: 4 vCPU, 16GB RAM
* License type: Other

*Step 3(b): SMB migration*

.Steps

. Add the Windows worker installer

* For SMB migration, download the windows worker installer for Azure from NSS: <Placeholder link>. Then follow this link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/quick-create-portal[link] to learn how to create a Windows VM using these recommended settings:

** Image: Choose Windows Server 2022 
** Datacenter: Azure Edition - x64 Gen2
** Size: 4 vCPUs, 16 GB memory
** RDP port 3389 open 

. Move the Windows worker installer to the Windows VM
* Login to the Windows Worker VM using the Remote Desktop Protocol and copy the Windows worker installer to the Windows VM.
* Use Microsoft Windows App (Mac) or RDP (Windows) to create a remote session. Follow this link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/connect-rdp[link] to learn about RDP connections.


. Depending on your configuration, select the MacOS or Windows tab.
+
[role="tabbed-block"]
====
.MacOS
--
Windows worker for MacOS.

.. Install the Microsoft Windows App on your local laptop.
.. Follow this link:https://learn.microsoft.com/en-us/windows-app/get-started-connect-devices-desktops-apps[link] to RDP into the SMB Windows Worker VM and use this link:https://learn.microsoft.com/en-us/windows-app/device-audio-folder-redirection-teams?tabs=macos#folder-redirection[link] to mount the local folder which contains the Windows Worker Installer.
.. Locate the folder you mounted to the Windows Worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM.
--
.Windows
--
Windows worker for Windows:

.. Launch a Remote Desktop Connection.
.. Follow this link:https://cat.pdx.edu/platforms/windows/remote-access/file-sharing-rdp-from-windows/[link] to RDP into the SMB Windows Worker VM and mount the local folder containing the Windows Worker Installer. 
.. Locate the folder you mounted to the Windows Worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM .
--
====

*Step 4: Connect to the control plane VM*

After you create the control plane VM, you can connect to validate if NDM is active.

.Steps

.. Install Azure CLI. Refer to the Azure CLI Download instructions.
.. SSH Into your control plane server. If your server does not have Public IP, you can use Azure bastion to configure SSH Access. Follow this link:https://learn.microsoft.com/en-us/azure/bastion/quickstart-host-portal[link] to learn how.
.. Switch the user to datamigrator:
+
[source,cli]
----
sudo su - datamigrator
----
.. Check the status of boot service and logs:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
Optionally, check the boot service logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
.. If you see "Datamigrator Application Setup Complete" in the logs, it indicates the setup is complete.
.. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----

You can now access NDM using RDP with the Windows VM created for NDM access and the control plane private IP address.

The default credentials for the NDM UI are:

* URL: https://<control-plane-private-ip>/
* Username: admin@datamigrator.local
* Password: Welcome@123

. Depending on your migration, select the NFS or SMB tab.
+
[role="tabbed-block"]
====
.NFS
--
Associate Linux worker with control plane VM.

.Steps

. Login to the Windows VM using RDP to access NDM.
* Use Microsoft Windows App (Mac) or Remote Desktop Connection (Windows) to create a RDP session.
* You can use this link:https://learn.microsoft.com/en-us/azure/virtual-machines/windows/connect-rdp[link] to learn about RDP connections.
. Retrieve the private IP address from the newly created control plane VM in Azure.
. Open any browser and navigate to the NDM UI using the following credentials: 
* IP address: https://<control_plane_IP_address>/
* Username: admin@datamigrator.local
* Password: Welcome@123.
. Reset the password.
. Add new user details and email ID.
. Create a new project by providing a name and an optional description.
. Select *View Instructions to Setup Worker* and copy the instructions. 
. To associate the Linux worker with the CP,
SSH into your worker server. If your server does not have Public IP, you can use link:https://learn.microsoft.com/en-us/azure/bastion/quickstart-host-portal[Azure bastion] to configure SSH Access. 
* Log in as root user:
+
[source,cli]
----
sudo su -
----
* Paste the instructions copied from *View Instructions to Setup Worker* to register the worker VM.
* Verify the status of the worker:
systemctl status datamigrator-worker.service
* Check the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
* Navigate to the NDM UI and verify that the worker is registered.
--

.SMB
--
Associate Windows worker with control plane VM
.Steps

. Run the Windows Worker Installer that you copied to the Windows Worker Server.
. Enter the following details when prompted. You can get these details from the NDM UI under *Home > View Instructions to Setup Worker:*
* Worker ID
* Worker secret
* Project ID
* Control plane Private IP address

. When installation completes, the worker service starts automatically and you can then locate the Logs at:
+
[source,cli]
----
C:\datamigrator\logs
----
. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name> -Wait
----
. Open the command prompt (cmd) as Administrator and run the following commands to manage the Service:
* Start the service:
+
[source,cli]
----
net start DatamigratorWorker
----
Stop the service:
+
[source,cli]
----
net stop DatamigratorWorker
----
Restart the service:
+
[source,cli]
----
net stop DatamigratorWorker && start DatamigratorWorker
----
--
====

You should consider the following when installing NDM using Azure

* *SAS URLs are time-limited*: Start your copy operation as soon as possible—typically within 7 days.

* *Validate copy is complete*: Do not use a partially copied VHD for deployments.

* *Checksum validation is recommended*: This ensures your VHD’s integrity matches the original source.

* *Repeat the full process* for each VHD (Control Plane and Worker).

*REFERENCE TABLE*
|===
| Placeholder | Description

| <YOUR_STORAGE_ACCOUNT>	 | Destination storage account name
| <YOUR_RESOURCE_GROUP>	 | Resource group name
| <YOUR_AZURE_REGION> | Azure region (e.g., East us)
| YOUR_CONTAINER_NAME| Container for VHD storage
| YOUR_STORAGE_ACCOUNT_KEY| Storage account access key
| <YOUR_SUBSCRIPTION_ID>| Azure subscription ID
| <YOUR_TENANT_ID>	| Azure tenant ID
| <YOUR_IMAGE_NAME>	| Name for the managed image
| <PROVIDED_SAS_URL>| The SAS URL provided by our team
| <VHD_FILE_NAME>	| VHD file name (without .vhd extension)
| <SHA_FILE_NAME>	| Checksum file name (without .sha256 extension)
|===








