---
sidebar: sidebar
permalink: install-using-azure.html
keywords: 
summary: 
---
= Prepare for NDM installation using Azure
:icons: font
:imagesdir: ./media/

[.lead]
Use Azure to install NetApp Data Migrator (NDM).

.About this task

NDM has two main components that you need to install:

* The *control plane*, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

* *Workers* are virtual machines running on Linux, which supports the NFS protocol, or Windows, which supports the SMB protocol. You can install multiple workers based on your requirements:

** For shared message block (SMB) migration, use the Windows Worker Installer on a Windows VM.
** For NFS migration, use the Linux Worker.

.Before you begin

Before you can install the NDM control pane and worker, you must have:

* An active Azure subscription
* A Resource group set up in your desired region
* Sufficient disk space for data storage and VM deployment
* Azure command line interface (CLI) installed

.Steps

. If you do not have the Azure command line interface (CLI) already installed, go to link:install-azure-using-cli.html[Install Azure CLI and manage assets].
+
If you already have the Azure CLI installed, go to Step 2.

. link:create-control-plane-worker-vm.html[Install the NDM control plane and workers].

