---
sidebar: sidebar
permalink: install-using-ova.html
keywords: 
summary: 
---
= Install NDM using OVA
:icons: font
:imagesdir: ./media/

[.lead]
Use OVA (Open Virtual Appliance) templates in a VMWare vSphere environment to install the NetApp Data Migrator (NDM) tool.

.About this task

This procedure has two main components, the control plane and the worker.

The control plane is the central location for managing all migration jobs and you create it first.

The workers are either NFS or SMB and they carry out the data migration. You can install multiple workers based on your needs:

* For SMB migration, you use the Windows Worker Installer. You must install the Windows Worker Installer on a Windows VM.
* For NFS migration, you use the Linux Worker.

.Before you begin

* Download the control plane OVA from the NetApp Support site .
* If you’re using SMB migration, download the Windows Worker Installer from the NetApp Support Site.
* If you're using NFS migration. download the Worker OVA from the NetApp Support Site.

== Step 1: Create the control plane and worker VMs

Create the control plane and worker virtual machines (VMs) from the OVA files using the setup wizard.

.Steps

. Log into VMware vCenter
. Right click on *NDMCluster* and select *Deploy OVF Template*.
. Select  *Select an OVF template* and copy the link to OVA file that you downloaded from the NetApp Support Site.
. Select *Next*.
. Select  *Select a name and folder* and provide the following information:
* The name for the VM.
* The location for the new VM. Select the datacenter or destination folder.
. Select *Next*.
. Select  *Select a compute resource* and select the cluster or host where the VM will run.
. Check *Automatically power on deployed VM*
. Select *Next*.
. Select  *Review details*. Verify that the details that you entered are correct and select *Next*.
. Select *Select storage.*
* For *Select virtual disk format*, select “Thin Provision”.
* For *VM Storage Policy,* select the datastore for the VM files.
. Select *Select networks* and select the VM’s network.
. Select  *Ready to* complete and review the summary page.
. Select *Finish* to start the deployment for the control plane VM.
. Repeat steps 2 to 14 to create the worker VM.
. Record the server IP addresses for the control plane and the worker VMs. You need these IP addresses when you're setting up the worker VMs later in the procedure.

== Step 2: Connect to the control plane VM

After you first create the control plane, you need to connect to it using OVA images.

.Steps

. Use the SSH username and password provided during the deployment of OVF template to SSH to the VM:
+
[source,cli]
----
ssh ubuntu@<control-plane-server-IP>
----
You are logged into the VM as the ubuntu user.
. Switch the user to data migrator:
+
[source,cli]
----
sudo su – datamigrator
----
. Check the status of the boot service:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
. Check the status of the logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----

NOTE: Wait between five and ten minutes for the UI to load. If it is still loading after ten minutes, restart the service:

[source,cli]
----
systemctl start boot-microk8s.service
----

After the UI loads, you see an output similar to the following example:

[source,cli]
----
kubectl get pods -n datamigrator
NAME                               READY   STATUS    RESTARTS   AGE
admin-service-69fc46d98d-mf8td     2/2     Running   0          144m
config-service-747948d47f-9shtj    2/2     Running   0          144m
datamigrator-ui-d987bcd98-xjqcs    2/2     Running   0          144m
db-writer-5cc479dc6c-zz2jn         2/2     Running   0          144m
jobs-service-7d7c8d69db-q8pj5      2/2     Running   0          144m
reports-service-65cb4f8858-6vqdm   2/2     Running   0          144m
----

== Step 3: Set up the worker VM

When you set up the Windows or Linux worker for the first time, you need to verify the worker VM using custom OVA images.

.Steps

Depending on your environment, select the Linux Worker or Windows Worker tab, or both tabs if your configuration includes both NFS and SMB.

[role="tabbed-block"]
====
.Linux Worker
--
.. Navigate to the NDM UI on the control plane using the IP address recorded in step 16:
+
[source,cli]
----
https://<IP_address>/
----
.. Select *View instructions to set up worker* and SSH to the worker VM:
+
[source,cli]
----
ssh <user_ID>@<worker_server_IP>
----

NOTE: Don’t use the same worker secret and worker ID to create multiple workers.

.. Login as the root user:
+
[source,cli]
----
sudo su -
----
.. Paste the instructions copied in step 4
.. Verify the status of the worker:
+
[source,cli]
----
systemctl status datamigrator-worker.service
----
.. Check the status of the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
.. Navigate to NDM UI to verify that the worker is registered.
--

.Windows Worker
--
.. Run the Windows Worker Installer that you copied to the Windows server.
.. During installation, enter the following values when prompted. You can get the values from the NDM UI under *Home > View Instructions to Setup Worker*:
* Worker ID
* Worker secret
* Control plane IP address
.. After the installation completes, the worker service starts automatically.
* The installation directory is `C:\datamigrator\.` 
* Locate the Logs at `C:\datamigrator\logs.`
.. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name> -Wait"
----
--
====

== Step 4: Manage worker credentials

The control plane and worker credentials are stored in OpenBao. Access the OpenBao and PostgreSQL application components to manage credentials.

.Steps

. Navigate to the NDM UI:
+
[source,cli]
----
https://<IP_address>/
----
. SSH into the control plane server to fetch the OpenBao root token:
+
[source,cli]
----
ssh <User_ID>@<control_plane_server_IP>
sudo su - datamigrator
cat /opt/datamigrator/openbao/cluster-keys.json
----
. Log in to OpenBaoUI using the root token from Step 2:
+
[source,cli]
----
https://<IP_address>/ui/
----
. Navigate to the following secret UIs after opening the OpenBao UI:
* Keycloak UI: `https://<IP_address>/keycloak/`
* Temporal UI: `https://<IP_address>/temporal/ui/`
. Use the control plane IP address to connect to the postgres database.
* Log in using the username and password from OpenBao.
* Postgres keys: `POSTGRES_DMADMIN_USER` and `POSTGRES_DMADMIN_PASSWORD`

== What's next?

link:configure-ndm.html[Set up and configure NDM]
