---
sidebar: sidebar
permalink: install-on-google-cloud.html
keywords: 
summary: 
---
= Install NDM on Google Cloud 
:icons: font
:imagesdir: ./media/

[.lead]
---
Install NetApp Data Migrator (NDM) on Google Cloud.

.About this task

This procedure has two main components, the control plane and the worker.

The control plane, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

Workers are virtual machines running on Linux, which supports the NFS protocol, or Windows, which supports the SMB protocol. You can install multiple workers based on your needs:

* For SMB migration, use the Windows Worker Installer. You must install the Windows Worker Installer on a Windows VM.
* For NFS migration, use the Linux Worker.

.Before you begin

* Download the control plane image from the NetApp Support Site.
* If you're using SMB migration, download the Windows Worker Installer from the NetApp Support Site.
* If you're using NFS migration, download the Worker image from the NetApp Support Site.
* Ensure that the ports for the control plane and workers are enabled:
+
include::./_include/configure-ports.adoc[]

== Step 1: Enable required APIs

link:https://cloud.google.com/migrate/virtual-machines/docs/5.0/get-started/enable-services#enabling_required_services_on_the_host_project[Enable all of the APIs required for your project^]. These APIs are mandatory for image import and deployment operations.

== Step 2: Prepare import destination

Learn how to link:https://cloud.google.com/storage/docs/creating-buckets#console[create a Google Cloud Storage (GCS) bucket^], if you have not already created one.

== Step 3: Set Up IAM roles and permissions

Ensure that the migration API has the required access permission. 

[role="tabbed-block"]
====
.Update disk permissions
--
Learn about link:https://cloud.google.com/migrate/virtual-machines/docs/5.0/migrate/image_import#add-disk-to-storage[disk storage permissions^] 
--
.Use "vmmigration" service
--
Use the "vmmigration" service. 

.Steps

. Assign the service account objectViewer access to your destination Cloud Storage bucket:
+
[source,cli]
----
gcloud storage buckets add-iam-policy-binding gs://<GCS_BUCKET> \
  --member=serviceAccount:service-<PROJECT_NUMBER>@gcp-sa-vmmigration.iam.gserviceaccount.com \
  --role=roles/storage.objectViewer
----
+
The service account needs roles/storage.objectViewer permission to read the VM image files from your Cloud Storage bucket during the migration process. 
+
When the VM Migration API is enabled, Google Cloud automatically provisions a service account with the following format:
+
`service-<PROJECT_NUMBER>@gcp-sa-vmmigration.iam.gserviceaccount.com` 
+
* `++ gcp-sa` is the Google Cloud Platform Service account  
* `vmmigration` is the VM Migration service identifier
* `iam.gserviceaccount.com` is the standard domain for Google Cloud service accounts

. Make yourself an admin user on the "vmmigration" service:
+
[source,cli]
----
gcloud projects add-iam-policy-binding <PROJECT_ID> \
  --member=user:<YOUR_EMAIL> \
  --role=roles/vmmigration.admin
----
+
This gives you VM migration administrative permissions at the project level. 
--
====

== Step 4: Obtain and upload images

//* Log into link:https://mysupport.netapp.com/site/[NetApp Support Site^] to download the control plane and worker .tar.gz images as well as (optional) .sha256 checksum files.
* Go to the preview link provided to download the control plane and worker .tar.gz images as well as (optional) .sha256 checksum files.
* link:https://cloud.google.com/storage/docs/uploading-objects#uploading-an-object[Upload the tar.gz for worker and control plane to your GCS bucket^].

== Step 5: Validate SHA256 checksums (optional)
//After you download the tar.gz file, you can optionally use this link:https://emn178.github.io/online-tools/sha256_checksum.html[checksum calculator^] to verify the checksum and validate against the checksum file downloaded from NSS.
After you download the tar.gz file, you can optionally use this link:https://emn178.github.io/online-tools/sha256_checksum.html[checksum calculator^] to verify the checksum and validate against the checksum file downloaded from the preview site.

== Step 6: Import images using VM migration service
After you upload the worker and control plane tar.gz files, you can create a VM image for worker and control plane:

[source,cli]
----
gcloud migration vms image-imports create <IMAGE_IMPORT_NAME> \
  --source-file=gs://<GCS_BUCKET>/<IMAGE_NAME>.tar.gz \
  --image-name=<IMAGE_NAME> \
  --location=<REGION> \
  --target-project=projects/<PROJECT_ID>/locations/global/targetProjects/<PROJECT_ID> \
  --project=<PROJECT_ID>
----
This creates a new GCP VM image from your archive, in the specified region.

== Step 7: List and confirm import completion

Run the following command to list the import tasks and confirm that the import was successful:
[source,cli]
----
gcloud migration vms image-imports list --location=<REGION> --project=<PROJECT_ID>
----
Wait for SUCCEEDED status before you proceed to VM creation.

== Step 8: Create VM instances
You need to create a Windows VM to access NDM using the Remote Desktop Protocol.

.Steps
. Create the control plane VM to access NDM.
+
.. Learn how to link:https://cloud.google.com/compute/docs/create-windows-server-vm-instance[create a Windows Server VM instance^]. Use the following recommended settings:
+
* Image: Windows Server 2022 Datacenter
* Size: 16 vCPU, 64 GB RAM
* RDP port 3389 open.
+
.. link:https://cloud.google.com/compute/docs/instances/connecting-to-windows[Connect to the Windows VM created using RDP^]. You can then access NDM.

. Create the control plane VM using the control plane image imported previously.
+
Learn how to link:https://cloud.google.com/compute/docs/instances/create-vm-from-custom-image[create a VM from a custom imported image^]. Use the following recommended settings:
+
* Size: 16 vCPU, 64 GB RAM
* Image: Custom imported image for the control plane.

. For NFS migration, create the Linux worker using the control plane image imported previously. 
+
Learn how to link:https://cloud.google.com/compute/docs/instances/create-vm-from-custom-image[create a VM from a custom imported image^]. Use the following recommended settings:
+
* Size: 4 vCPU, 16 GB RAM
* Image: Custom imported image for the control plane.

. For SMB migration, add the Windows worker installer:
//.. Download the windows worker installer for Google Cloud Platform from the link:https://mysupport.netapp.com/site/[NetApp Support site^]. 
.. Download the windows worker installer for Google Cloud Platform from the preview link provided. 
.. Learn how to link:https://cloud.google.com/compute/docs/create-windows-server-vm-instance[create a Windows Server VM instance^]. Use the following recommended settings for the Windows worker VM:
+
* Image: Windows Server 2022 Datacenter
* Size: 16 vCPU, 64 GB RAM.
* RDP port 3389 open

.. Move the Windows worker installer to the Windows VM:

... Login to the Windows Worker VM using RDP and copy the Windows worker installer to the Windows VM.
... Use Microsoft Windows App (Mac) or Remote Desktop Connection (Windows) to create an RDP session.
... link:https://cloud.google.com/compute/docs/instances/connecting-to-windows[Connect to the Windows VM using RDP^].

. Depending on your configuration, select the MacOS or Windows tab.
+
[role="tabbed-block"]
====
.MacOS
--
Windows worker for MacOS.

.. Install the Microsoft Windows App on your local laptop.
.. link:https://learn.microsoft.com/en-us/windows-app/get-started-connect-devices-desktops-apps[RDP into the SMB Windows Worker VM^].
.. link:https://learn.microsoft.com/en-us/windows-app/device-audio-folder-redirection-teams?tabs=macos#folder-redirection[Mount the local folder which contains the Windows Worker Installer^].
.. Locate the folder you mounted to the Windows Worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM.
--
.Windows
--
Windows worker for Windows:

.. Launch a Remote Desktop Connection.
.. link:https://cat.pdx.edu/platforms/windows/remote-access/file-sharing-rdp-from-windows/[RDP into the SMB Windows Worker VM and mount the local folder containing the Windows Worker Installer^]. 
.. Locate the folder you mounted to the Windows Worker VM under "This PC" on the server.
.. Move the Windows Worker Installer from the mounted folder to a suitable location on the Windows VM .
--
====

. Connect to the control plane VM:

.. Use SSH to connect to the control plane VM:
+
[source,cli]
----
gcloud compute ssh <control-plane-instance-name> --internal-ip --zone <zone-name>
----

.. Switch the user to datamigrator:
+
[source,cli]
----
sudo su - datamigrator
----
.. Check the status of boot service and logs:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
Optionally, check the boot service logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
.. If you see "Datamigrator Application Setup Complete" in the logs, this indicates the setup is complete.
.. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----
+
You can now access NDM using RDP with the Windows VM you created for NDM access and the control plane private IP address.
+
The default credentials for the NDM UI are:
+
* URL: `https://<control-plane-private-ip>/`
* Username: admin@datamigrator.local
* Password: Welcome@123

. Depending on your migration, select the NFS or SMB tab:
+
[role="tabbed-block"]
====
.NFS
--
Associate Linux worker with control plane VM.

.. Login to the Windows VM using RDP to access NDM.
* Use Microsoft Windows App (Mac) or Remote Desktop Connection (Windows) to create an RDP session.
* link:https://cloud.google.com/compute/docs/instances/connecting-to-windows[Connect to the Windows VM using Remote Desktop Protocol (RDP)^].
.. Retrieve the private IP address from the newly created control plane VM in GCP.
.. Open any browser and navigate to the NDM UI using the following credentials: 
* IP address: `https://<control_plane_IP_address>/`
* Username: admin@datamigrator.local
* Password: Welcome@123
.. Reset the password.
.. Add new user details and email ID.
.. Create a new project by providing a name and an optional description.
.. Select *View Instructions to Setup Worker* and copy the instructions. 
.. To associate the Linux worker with the CP, use SSH to connect to your worker server. If your server does not have Public IP, you can use bastion to configure SSH access. 
* Log in as root user:
+
[source,cli]
----
sudo su -
----
* Paste the instructions copied from *View Instructions to Setup Worker* to register the worker VM.
* Verify the status of the worker:
[source,cli]
----
systemctl status datamigrator-worker.service
----
* Check the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
* Navigate to the NDM UI and verify that the worker is registered.
--

.SMB
--
Associate Windows worker with control plane VM

.. Run the Windows Worker Installer that you copied to the Windows Worker Server.
.. Enter the following details when prompted. You can get these details from the NDM UI under *Home > View Instructions to Setup Worker:*
* Worker ID
* Worker secret
* Project ID
* Control plane Private IP address

.. Disable Windows defender:
+
[source,cli]
----
PS C:\Windows\system32> Set-MpPreference -DisableRealtimeMonitoring $true
----
+
[source,cli]
----
PS C:\Windows\system32> Add-MpPreference -ExclusionPath "C:\datamigrator\mnt"
----

.. Disable Windows update in Windows services.

.. When installation completes, the worker service starts automatically and you can then locate the Logs at:
+
[source,cli]
----
C:\datamigrator\logs
----
.. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name> -Wait
----
.. Open the command prompt (cmd) as Administrator and run the following commands to manage the Service:
* Start the service:
+
[source,cli]
----
net start DatamigratorWorker
----
Stop the service:
+
[source,cli]
----
net stop DatamigratorWorker
----
Restart the service:
+
[source,cli]
----
net stop DatamigratorWorker && start DatamigratorWorker
----
--
====

The following tables describes the placeholder references:

|===
| Placeholder | Description

| <PROJECT_ID>	 | Your GCP project ID
| <PROJECT_NUMBER>	 | Your GCP project number
| <GCS_BUCKET> | Your GCS bucket name
| <IMAGE_NAME>| VM image name (without extension)
| <IMAGE_IMPORT_NAME>| Unique name for the import task
| <REGION>| Your region. For example, US EAST 4.
|===


.Related information

* link:https://cloud.google.com/migrate/virtual-machines/docs/5.0/get-started/enable-services#enabling_required_services_on_the_host_project[Enable Image Import APIs^]
* link:https://cloud.google.com/migrate/virtual-machines/docs/5.0/migrate/image_import#add-disk-to-storage[Add Disk to Storage^]
* link:https://cloud.google.com/compute/docs/instances/create-vm-from-custom-image[Create VM from Custom Image^]
* link:https://cloud.google.com/compute/docs/create-windows-server-vm-instance[Create Windows Server VM^]
* link:https://cloud.google.com/storage/docs/uploading-objects#uploading-an-object[Upload objects to GCS^]

.What's next?

link:configure-ndm.html[Learn about configuring NDM]

// 2025 DEC 1, OTHERDOC-168
// 9 OCT 2025, commented out lines with the NSS link and replaced them with "preview link provided" - temporary measure for preview only.