---
sidebar: sidebar
permalink: install-using-ova.html
keywords: 
summary: 
---
= Install NDM using OVA
:icons: font
:imagesdir: ./media/

[.lead]
Use OVA (Open Virtual Appliance) templates in a VMWare vSphere environment to install NetApp Data Migrator (NDM).

.About this task

This procedure has two main components, the control plane and the worker.

The control plane, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

Workers are virtual machines running on Linux (which supports the NFS protocol), or Windows (which supports the SMB protocol) and carry out the data migration. You can install multiple workers based on your needs:

* For SMB migration, use the Windows Worker Installer. You must install the Windows Worker Installer on a Windows VM.
* For NFS migration, use the Linux Worker VM.

.Before you begin

//* Download the control plane OVA from the link:https://mysupport.netapp.com/site/[NetApp Support site^].
//* For SMB migration, download the Windows Worker Installer from the link:https://mysupport.netapp.com/site/[NetApp Support site^].
//* For NFS migration, download the Worker OVA from the link:https://mysupport.netapp.com/site/[NetApp Support site^].
* Download the control plane OVA from the preview link provided.
* For SMB migration, download the Windows Worker Installer from the preview link provided.
* For NFS migration, download the Worker OVA from the preview link provided.
* Ensure that the ports for the control plane and workers are enabled:
+
include::./_include/configure-ports.adoc[]

[[create-control-plane-and-worker-vms]]
== Step 1: Create the control plane and worker VMs

Create the control plane and worker virtual machines (VMs) from the OVA files using the setup wizard.

.Steps

. Log into VMware vCenter.
. Select  *Select an OVF template* and upload the file that you downloaded from the NetApp Support Site.
. Select *Next*.
. Select  *Select a name and folder* and provide the following information:
* The name for the VM.
* The location for the new VM.Select the datacenter or destination folder.
. Select *Next*.
. Select  *Select a compute resource* and select the cluster or host where the VM will run.
. Check *Automatically power on deployed VM*.
. Select *Next*.
. Select  *Review details*. Verify that the details that you entered are correct and select *Next*.
. Select *Select storage.*
* For *Select virtual disk format*, select *Thin Provision*.
* For *VM Storage Policy,* select the datastore for the VM files.
. Select *Select networks* and select the VM's network.
. Optionally, select *Customize template* to provide a static IP address to the VM. You can use DHCP, the NDM vCenter, or your own vCenter:
+
[role="tabbed-block"]
====
.DCHP
--
To use DHCP (Dynamic IP), keep the network settings blank.
--
.NDM vCenter
--
To use the NDM vCenter, locate the reference for the custom properties in*vCenter OVA Deployment Custom Details*.
--
.Own vCenter
--
If you are using your own vCenter, provide the following details for your network:

* *SSH Username*:User account for SSH operations
* *SSH Password*:Password for the SSH user
* *IPv4 Address*: VM assigned fixed IP address
* *IPv4 Subnet Netmask*:Default route for network traffic
* *IPv4 Gateway*: Defines the subnet range
* *Primary DNS*:Main domain name resolver
* *Secondary DNS*:Backup domain name resolver
* *Search domains*:DNS search suffixes
--
====

. Select *Ready* to complete and review the summary page.
. Select *Finish* to start the deployment for the control plane VM.
. Repeat steps 2 to 14 to create the worker VM.
. Record the server IP addresses for the control plane and the worker VMs. You need these IP addresses when you're setting up the worker VMs later in the procedure.
. Use the SSH username and password provided during the OVA deployment to connect using SSH.

== Step 2: Connect to the control plane VM

By establishing an SSH connection to the control plane VM, you can review pod logs and status.

.Steps

. Use the SSH username and password provided during the deployment of OVF template to SSH to the VM:
+
[source,cli]
----
ssh <username>@<control-plane-server-IP>
----
You are logged into the VM as the ubuntu user.
. Switch the user to data migrator:
+
[source,cli]
----
sudo su - datamigrator
----
. Check the status of the boot service:
+
[source,cli]
----
sudo systemctl status boot-microk8s.service
----
. Check the status of the logs:
+
[source,cli]
----
tail -10f /opt/datamigrator/logs/ndm-first-boot.log
----
The final two lines of output from this command should be similar to the following:
+
[source,cli]
----
2025-08-13 05:34:29 MicroK8s cloud init setup completed successfully
2025-08-13 05:34:30 Datamigrator Application Setup Complete
----

. Verify that all the pods are up and running:
+
[source,cli]
----
kubectl get pods -n datamigrator
----
+
NOTE: Wait between ten and fifteen minutes for the UI to load. If it is still loading after ten minutes, restart the service:
+
[source,cli]
----
systemctl start boot-microk8s.service
----
+
After the UI loads, you should see an output similar to the following example:
+
----
kubectl get pods -n datamigrator
NAME                               READY   STATUS    RESTARTS   AGE
admin-service-69fc46d98d-mf8td     2/2     Running   0          144m
config-service-747948d47f-9shtj    2/2     Running   0          144m
datamigrator-ui-d987bcd98-xjqcs    2/2     Running   0          144m
db-writer-5cc479dc6c-zz2jn         2/2     Running   0          144m
jobs-service-7d7c8d69db-q8pj5      2/2     Running   0          144m
reports-service-65cb4f8858-6vqdm   2/2     Running   0          144m
----

The default credentials for the NDM UI are:

* URL: `https://<control-plane-private-ip>/`
* Username: admin@datamigrator.local
* Password: Welcome@123

== Step 3: Associate worker VM with control plane

You need to add the worker VM to the control plane created in <<create-control-plane-and-worker-vms,Step 1>>, for the first time.

.Steps

Depending on your configuration, select either the Linux worker (NFS) or Windows worker (SMB) steps below. If your configuration includes NFS and SMB, refer to both sets of steps.


[role="tabbed-block"]
====
.Linux Worker
--
. Navigate to the NDM UI on the control plane using the IP address recorded in step 16:
+
[source,cli]
----
https://<IP_address>/
----
. Select *View instructions to set up worker* then copy these instructions.
. SSH to the worker VM:
+
[source,cli]
----
ssh <user_ID>@<worker_server_IP>
----
+
NOTE: Don’t use the same worker secret and worker ID to create multiple workers.

. Login as the root user:
+
[source,cli]
----
sudo su -
----
. Paste the instructions copied in step 2.
. Verify the status of the worker:
+
[source,cli]
----
systemctl status datamigrator-worker.service
----
.. Check the status of the logs:
+
[source,cli]
----
tail -20f /opt/datamigrator/logs/datamigrator-worker.log
----
.. The output of this command should be similar to the following example:
+
[source,cli]
----
datamigrator-worker.service - Datamigrator Worker Service
     Loaded: loaded (/etc/systemd/system/datamigrator-worker.service; enabled; preset: enabled)
     Active: active (running) since Tue 2025-08-12 11:33:54 IST; 1 day 3h ago
   Main PID: 697 (dm-worker-linux)
      Tasks: 40 (limit: 4599)
     Memory: 1.8G (peak: 2.1G)
        CPU: 58min 5.437s
     CGroup: /system.slice/datamigrator-worker.service
             ├─697 /opt/datamigrator/binary/dm-worker-linux-x64-v1.0.0
             ├─908 bash
             ├─909 bash
             ├─910 bash
             ├─911 bash
             └─912 bash

Aug 12 11:33:54 datamigrator systemd[1]: Started datamigrator-worker.service - Datamigrator Worker Service.----
----

. Navigate to NDM UI to verify that the worker is registered.
--

.Windows Worker
--
. Create a Windows VM and copy the Windows Worker Installer to this Windows VM.
. Run the Windows Worker Installer that you copied to the Windows VM.
. During installation, manually enter the following values when prompted. You can get the values from the NDM UI under *Home > View Instructions to Setup Worker*:
+
* Worker ID
* Worker secret
* Control plane IP address
. After the installation completes, the worker service starts automatically.
+
* The installation directory is `C:\datamigrator\.` 
* Locate the Logs at`C:\datamigrator\logs.`
. Follow the logs in real-time by opening PowerShell and running the following command:
+
[source,cli]
----
Get-Content -Path "C:\datamigrator\logs\<log_file_name> -Wait"
----

. Disable Windows defender:
+
[source,cli]
----
PS C:\Windows\system32> Set-MpPreference -DisableRealtimeMonitoring $true
----
+
[source,cli]
----
PS C:\Windows\system32> Add-MpPreference -ExclusionPath "C:\datamigrator\mnt"
----

. Disable Windows update in Windows services.
--
====

== Step 4: Manage worker credentials

The control plane credentials are stored inOpenBao. Access the OpenBao andPostgreSQL application components to manage credentials.

.Steps

. Navigate to the NDM UI:
+
[source,cli]
----
https://<IP_address>/
----
. Use SSH to connect to the control plane server to fetch the OpenBao root token:
+
[source,cli]
----
ssh <User_ID>@<control_plane_server_IP>
sudo su - datamigrator
cat /opt/datamigrator/openbao/cluster-keys.json
----
. Log in to the OpenBao UI using the root token from Step 2:
+
[source,cli]
----
https://<IP_address>/ui/
----
. Navigate to the following secret UIs after opening the OpenBao UI:
* KeycloakUI: `https://<IP_address>/keycloak/`
* TemporalUI: `https://<IP_address>/temporal/ui/`
. Use the control plane IP address to connect to the postgres database.
* Log in using the username and password from OpenBao.
* Postgres keys: POSTGRES_DMADMIN_USER and POSTGRES_DMADMIN_PASSWORD

.What's next?

link:configure-ndm.html[Learn about configuring NDM]

// 2025 DEC 1, OTHERDOC-168
// 9 OCT 2025, commented out lines with the NSS link and replaced them with "preview link provided" - temporary measure for preview only.