---
sidebar: sidebar
permalink: known-issues.html
keywords: 
summary: 
---
= Known issues and workarounds
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Data Migrator (NDM) has the following known issues.

== Workflows

=== Job Run status can be confusing when errors occur

Some Migration job runs encounter errors and show a "Completed" migration status, while others show an "Errored" status. This difference can cause confusion when interpreting the Migration job run status. 

Status definitions:

* Completed: A job run has finished, but might contain errors.

* Errored: A job run failed due to a critical issue.

.Workaround

Verify the job run outcome by checking the job run details for any errors, especially if the status is "Completed". Do not rely only on the status label until after you address this issue.

=== Migrations fail for jobs in "Inactive" state

During data migration, the following error message might appear:

----
Source Path: <source-path> & Destination Path: <destination-path> failed due to Inactive job found. Please reactivate or remove the existing job.
----

This issue occurs when NDM updates migration paths but can't find an active job associated with them. Recreating the path does not activate the job; you must update it manually.

.Workaround
Go to (http://<control-plane-IP-address>/jobs-list) in NDM, manually set the job configuration to *Active*, then restart the migration job. 

=== Incorrect file listing during cutover without delta changes

The UI might show files as migrated, even if the source data has not changed. This is a display issue and does not affect actual data integrity. 

.Workaround

* If you previously scheduled incremental sync then no action is required because the next sync will run automatically. 

* If an incremental sync is not scheduled, you can manually trigger an incremental migration.

* For your next bulk migration, enable automatic incremental migrations by choosing either “Schedule” or “Cron Expression” at Step 2 (Options-  Incremental Sync Schedule). This option is disabled, by default.

After incremental sync has completed, then:

* If NDM reports 0 files, your source and destination are in sync. 
* If NDM reports files, re-run the migration until it shows 0 files. Then start cutover.

=== Update to file server protocol version requires page refresh to update the export path list

When you update a file server protocol version, NDM requires you to perform a page refresh to update the export path list. If you don't, you might cause compatibility issues, delays in fetching the export list, or incomplete updates. This might lead to data inconsistencies, failed synchronization, or errors in accessing the latest export information.  

.Workaround

Refresh the page whenever you update the file server protocol version. 

=== Job paused or stalled (no progress in Running state) for more than 20 minutes

NDM might require user intervention when network connectivity issues, or issues with source, destination volume stability, or both are observed. The job might be in the "Paused" state, or in the "Running" state without any visible progress. This pause might happen if the source or destination services go down, or if the worker service experiences downtime.

.Workaround

. Check the source and destination. 
+
If they are offline, restart to restore connectivity.  

. Check the worker status. 
+
If the worker is offline, SSH into the VM and run the following command: 
+
[source,cli]
----
systemctl restart datamigrator-worker.service
----
. Reboot the VM: 
+
If issue persists, restart the worker VM. 

 
== Validation

=== File sizes might differ after migration even if counts match

After data migration has completed, the total number of files is correct, but some files might have a different size compared to the original source. This can happen it the network is interrupted or if there are problems with the server during file transfer.

.Workaround

Review the migration COC report to identify files marked as errored. Then re-run the migration until the errors are resolved. 

=== Discovery job shows 0 files until control plane is refreshed

When running a discovery job, the Job Run Details page might initially show zero files or directories, even though the Discovery report preview displays the actual results.  This happens because the Control Plane updates every 10 minutes. During this interval, the Job Run Details might temporarily show outdated information, even if the job is marked as "Completed." 

.Workaround

* Wait for the dashboard to refresh (up to 10 minutes) the Job Run Details page, then accurate file and directory counts are displayed. 
* For immediate confirmation, refer to the Discovery Report Preview, which includes discovered files and directories. 

== Configuration 

=== Migration precheck displays false "Insufficient Space" warning*

During migration prechecks, you might see the following warning, even if the destination has sufficient space: 

----
Insufficient destination space for selected path. Do you still want to proceed with the migration? 
---- 

This can happen if you skip the discovery step and NDM uses a general command that reads the entire block device size instead of the actual dataset size. This can trigger a false warning. 

.Workaround

Run Discovery before a Migration run, to ensure disk usage information is available for pre-check operation. If you still see this warning, then: 

* Confirm that discovery has completed. 
* Manually verify the destination volume has enough space. 
* If there is sufficient space, you can safely proceed with data migration. 

=== Access permission mismatch when SID mapping is used

NDM might report an error (Missing ACE in target) indicating an access permission mismatch between the source and target systems when SID mapping is used. This issue occurs because SID mapping was not performed at the ROOT level.   

.Workaround

Provide the CSV mapping for the SID source and target as shown in the following two scenarios:  

Scenario 1:: 
+
For users or groups deleted or removed from the source Active Directory, provide the SID in the CSV mapping sheet:
+
*Example* 
+
|===
| sid_source | sid_target

| S-1-5-21-2444020195-1862089444-1769087368-1000 
| S-1-5-21-3481156262-2863848796-4292454742-512

|===

Scenario 2:: 
+
For active users or groups in Active Directory, provide usernames or group names in the CSV mapping sheet exclusively in lowercase, including the domain prefix, for example, domain\username. 
+
*Example*:  
+
|===
| sid_source | sid_target 

| rootdomain\user1 | rootdomain\user2 

|===


== Reporting 

=== COC report contains files from deleted folders
The Chain of Custody (COC) report might list files from deleted folders. When you delete a folder in the source, NDM correctly mirrors the deletion by removing the folder from the destination. However, files that were previously contained in that folder might still appear in the COC report.

.Workaround

Check the destination volume because the data is correctly mirrored even though the COC report might show entries from deleted folders.
=== Excel displays incorrect permissions in COC report file

When opening the COC report CSV file in Microsoft Excel, some file or folder permissions might appear as #NAME? instead of the actual values, for example, -rwxrwxrwx. 

This happens because Excel mistakenly treats certain permission strings (starting with - or =) as formulas, leading to display errors. (The CSV file itself is correct, this is only a display issue).  

.Workaround

To view correct file and folder permissions open the CSV file using one of the following applications: 

* Google Sheets 

* Apple Numbers 

* Online CSV viewer 

* Text editor, for example, Notepad++ 

=== Unable to switch user on Windows worker

Switching to a different user account on Windows worker might fail due to existing network connections. This can prevent access to the file server. 

.Workaround 


To remove the previous connection, open Command Prompt on the Windows worker and run the following commands:

[source,cli]
----
net use
----

[source,cli]
----
net use <IP address> /delete
----

You can then switch to the new user account and access the file server. 

== Recommendations for using NDM

* Ensure that the following ports for the control plane and workers are enabled:
+
*Control plane*
+
[cols="1,1,1"]
|===
|Service | TCP port | Notes

.2+| Temporal Server | 7233 | Frontend for workers and clients
| 7234 |	Internode connection, if using clusters
| Temporal UI | 8080  | Default port, if enabled
| PostgreSQL (Temporal database) | 5432 | From Temporal services
| Redis | 6379 | From workers or control plane services
| API or UI ingress (your app) | 80 or 443, as applicable  |	
| Grafana | 3000 |	
|===
+
*Workers*
+
[cols="1,1,1"]
|===
|Service |TCP port | Connect to...

.3+|Outbound to Control plane | 7233 | Temporal frontend
| 6379 | Redis
| 80 or 443 | API or UI, if they call it
.2+| Outbound to storage |NFS: 2049 |NFS servers 

(Include 111 TCP/UDP if the portmapper service for Remote Procedure Calls is needed) | SMB: 445  | SMB servers
|===

* Do not run Migration and Cutover jobs simultaneously. Ensure only one job is active at any time. 

* Use one worker secret code to set up a worker explicitly. 

CAUTION: Don't restart or reboot the control plane. Contact NDM support at ndm-support@netapp.com for assistance.

// 2025 DEC 1, OTHERDOC-166 and NADIAA updates