---
sidebar: sidebar
permalink: learn-about-install.html
keywords: aws installation, prerequisites, control plane, worker vm, ec2
summary: "Learn about installing the NetApp Data Migrator control plane and worker VMs."
---
= Learn about installing NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Data Migrator has the following two components that you need to install to run migration jobs: 

* *Control plane*: The control plane acts as the central management and orchestration layer. You deploy the control plane on a Linux virtual machine (VM), then you deploy the workers.

* *Workers*: Workers are virtual machines that perform the actual data migration. You can deploy multiple workers based on scale and your requirements. The worker type depends on the protocol:  
+
** A Linux worker supports NFS migrations.
** A Windows worker supports SMB migrations. 

NetApp Data Migrator provides images for the control plane and Linux workers. The NDM team provides the executable to install Windows workers. You can contact the NetApp NDM team at ng-ndm-downloads@netapp.com to install the Windows worker, or locate them through the NetApp Support Site. 

You deploy the control plane virtual machine (VM) and Linux worker VM using the AWS, Azure, or Google Cloud service or Open Virtual Appliance (OVA) templates. Then you create the control plane and worker VMs to access NetApp Data Migrator. You create the control plane VM and Linux worker VM using the images that you deployed, and the Windows worker VM using the Windows Worker Installer.

.What's next?
Learn about link:deploy-control-plane-and-linux-workers.html[deploying a control plane VM and Linux worker VM]