---
sidebar: sidebar
permalink: manage-jobs.html
keywords: job management, discovery jobs, migration jobs, cutover jobs, job runs
summary: "Use job management features in NetApp Data Migrator to initiate and track discovery, migration, and cutover jobs and job runs."
---
= Manage jobs and job runs in NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
Use job management features in NetApp Data Migrator to initiate and track your *Discovery*, *Migration*, and *Cutover* jobs and job runs.

NOTE: Do not run Migration and Cutover jobs simultaneously. Ensure that only one job is active at a time. 

== View Job Config List

The *Job Config List* page provides a comprehensive overview of all migration related jobs. Use this page to monitor and manage the status and progress of *Discovery*, *Migration*, and *Cutover* jobs.

.Steps

. Log in to NetApp Data Migrator.
. Select *Jobs* > *Job Config List*.
+
The *Jobs Listings* table appears, which includes the following information:
+
* *Source*: The location of source file server.
* *Destination*: The destination file server and export path details for Migration jobs.
* *Protocol*: The protocol used by the job (NFS or SMB).
* *Next Schedule*: The next scheduled execution time (if applicable).
* *Runs*: The number of times the job has been executed.
* *Type*: The job type (Discovery, Migration, or Cutover).
* *Status*: The current state of a job can be either Active or Inactive. Jobs that use manual export paths with an invalid or disabled status automatically become inactive. Refer to link:manage-file-servers.html[Add and manage file servers] for more details.
* *Updated On*: Job update timestamp.
+
Jobs that use manual export paths or the export paths file are later re-uploaded. Any previously run jobs associated with a now invalid or disabled path automatically become inactive.
. Select *Filters* to sort the jobs in the Jobs Listings table. You can choose a combination of filters based on the following options:
+
* Source
* Destination
* Protocol
* Type
* Status
+
. Select *Clear all* to remove filters already applied to your job listings.

== Activate or deactivate a Job
From the Job Listings table, you can activate or deactivate a job.

.Steps

. Activate a job:
.. Select *Jobs* > *Job Config List*.
.. In the Job Listings table, select the action menu next to the job you want to activate.
.. Select *Activate*. The job status changes to Active.

. Deactivate a job:
.. Select *Jobs* > *Job Config List*.
.. In the Job Listings table, select the action menu next to the job you want to deactivate.
.. Select *Deactivate*. The job status changes to Inactive, and execution stops until you reactivate the job.

== Edit job configurations 

.Steps 

. Select *Jobs* > *Job Config List*.
. <<view-job-details,Open the Job Details page>> for the job you want to edit.
. Select *View/Edit Configuration*.
. Edit the job configuration:
+
[role="tabbed-block"]
====
.Discovery Job
--
* Add or remove Excluded Path Patterns
* Schedule a job run
--
.Migration Job
--
* Edit any job option
* Add or remove mappings
* Schedule a job run
--
====
. Select *Save*. The new configuration affects future job runs.

NOTE: Changing the configuration, for example, disabling preserve permissions, after baseline migration is completed might result in an inconsistent state during subsequent migrations. Instead of changing the configuration, you should delete the current job and start a new job.

== Re-run errored files and directories 

If a migration job run completes with errors due to transient issues such as network timeouts or permission problems, you can use the retry feature to re-process only the failed items without re-running the entire migration. 

.Steps 

. Select *Jobs* > *Job Config List*. 
. In the *Job Listings* table, select the action menu next to the job that has failed items.
. Select *Details* > *Retry Recent Errors* > *Proceed with Retry* to start the retry operation. 

== Delete a Job 

.Steps 

. Select *Jobs* > *Job Config List*.
. In the *Job Listings* table,  select the action menu next to the job you want to delete. 
. Select *Delete* > *Delete*. 
+
NOTE: You can only delete a job if there is no active run. 

[[view-job-details]]
== View Job Details

From the *Job Config List* page, you can access the *Job Details* page to view additional details about individual jobs, such as:

* Job type (Discovery, Migration, or Cutover)
* Number of files and directories discovered
* Time elapsed
* Data discovered
* Job configuration 

.Steps

. Select *Jobs* > *Job Config List*.
. In the *Job Listings* table, select the action menu next to a job, then select *Details*.

== View Job Run History

On the *Job Details* page, the *Run History* table provides you with the information about previous job runs and the job status. 

The migration and discovery job status types include:

* *Ready*: A job is scheduled to run.
* *Running*: A job is in the running state.
* *Paused*: A job run has been paused manually or by NetApp Data Migrator. For example, a job can have a paused status if a worker goes down while the job is running.
* *Completed*: A job is complete.
* *Errored*: A job run triggers a fatal error.
* *Failed*: If a worker goes offline while a job is running, the job might enter a failed state.

The cutover job status types include:

* *Blocked*: The job is waiting for a user response.
* *Rejected*: The job has been reviewed and rejected by a user.
* *Approved*: The job has been reviewed and approved by a user. 
* *Stopped*: The job has stopped running.

== Manage Job Run operations

From the *Job Details* page, you can manage *Start*, *Stop*, *Pause*, and *Resume* operations for a job. Use the *Pause* feature to temporarily halt a running job, without canceling it. Then you can resume the job from the point where it was paused. This is a useful feature in scenarios where you need to free up system resources or troubleshoot issues without losing progress.

.Steps
. On the *Job Details* page, in the *Run History* table, select the action menu next to a running job.
. Pause or resume a job run:
.. Select *Pause*.
.. To Resume the job run, select *Resume*. 
+
The job status changes to *Running* and the job continues to run from the step where it was paused.

. Stop or start a job run:
+
You can use the stop option to permanently terminate a job run that is in progress. This action is useful when a job run is no longer required. You cannot resume a job run that is stopped but you have the option to start a new job run from the beginning.

.. Select *Stop*.
+
The job run status changes to *Stopped*.
.. To start a new job run, select *Adhoc Run*.
+
The job run status changes to *Running*.

== Access Job Run Details

From the *Run History* table, access the *Job Run Details* page where you can view additional details about your job runs.

.Steps

. On the *Job Details* page, in the *Run History* table, select the action menu next to a job run.
. Select *Details* to view the *Job Run Details* page, which includes the following information:
+
* *Discovery/Migration*: The job run type and status.
* *Files*: The number of files found during the discovery process.
* *Directories*: The number of directories found during the discovery process.
* *Elapsed Time*: How long the discovery process took.
* *Data Discovered*: The total size of discovered files.
* *Workers*: The number of workers assigned to the job.
* *Tasks*: The number of tasks being executed.
* *Task Status Indicators*:
** *Pending*: The number of Tasks waiting to be executed.
** *Running*: The number of Tasks currently in progress.
** *Completed*: The number of tasks that have successfully completed.
** *Errored*: The number of tasks that encountered issues during execution.
* *Job Name*: The name assigned to the job.
* *Source Path*: The path to the file being used for data discovery.
* *Protocol*: The protocol being used for discovery (NFS or SMB).
+
The lower right tile on the *Job Run Details* page lists the number of errors that occurred during migration (if any). Select *View All* to access the *Errors* page, where you can find more detailed information about these errors.

. Generate detailed reports that provide you with insights into job execution metrics including file counts, status, errors, and execution time. You can use these reports for review or auditing purposes.

* Select *Discovery Report* > *Preview* to view a histogram of job report data.
* Select *Download as CSV* to export a report in CSV format, which you can analyze using a spreadsheet application.
* Select *Download as PDF* . This option is ideal for document sharing.
* Select *View Logs* to view or download the log files using Grafana.

== View Migration Activity 

The Migration Activity page shows the ten oldest files currently being migrated. It also shows the total number of files in progress and provides an option to download a CSV file containing a complete list of these files. 

.Steps 

. From the *Run History* table, select *Job Run Details* for a running job.
. Select *Migration Activity*.

== Generate a job error report

You can generate an error report for jobs with an *Errored* status or for a previous job run. An error report can help you to understand why an error occurred.

.Steps

. Generate an error report for jobs with an *Errored* status:
.. On the *Job Details* page, in the Errors pane, select *View All*.
.. Select *Generate Error Report* to download details about errors in the latest job run.

. Generate an error report for a previous job run:
.. On the *Job Details* page, in the *Run History* table, select the action menu next to the job run for which you want to generate an error report.
.. Select *Details*.
.. On the *Job Details* page, in the *Errors* panel, select *View All*.
..  Select *Generate Error Report* to download details about errors in the job run you selected.

// 2026 APRIL 15, GA release
// 2026 FEB 25, Preview + 3 release
// 2026 JAN 12: OTHERDOC-184
// 2025 NOV 28: OTHERDOC-171 and NADIAA updates
