---
sidebar: sidebar
permalink: manage-projects.html
keywords: 
summary: 
---
= Create and manage projects in NDM
:icons: font
:imagesdir: ./media/

[.lead]
You can use the Projects tab in the NetApp Data Migrator (NDM) dashboard to quickly and easily create, edit, or switch between projects.

== Create a project

App admin users can create a new project in NDM and assign users with defined roles to that project.

.Steps

. Log in to NDM.
. Select *Settings* in the top navigation bar.
. Select the *Projects* tab to view a list of existing projects
. Select *Add Project* and a new window appears.
. Enter your *Project Name* and *Project Description (optional)*.
. Add users to your project:
* Select a *User* from the dropdown list.
* Assign a *Role* to the user (*App Admin*, *Project Admin* or *Project Viewer*).
* Select *+Add*.
. Select *Save and Confirm.*
. Select *Submit* and a confirmation message appears, stating that the project has been successfully created.

== Edit a project

You can quickly edit details about your project, if they need updating.

.Steps

. Select *Settings* in the top navigation bar.
. Select the *Projects* tab to view a list of existing projects.
. Select *(⋮)* next to the details of the project you wish to edit then select *Edit Project* from the dropdown menu.
. Update the Project Name, Project Description or add new users as required.
. Select *Submit* to save the changes.

== Switch between projects

If you are monitoring several projects at the same time, you can quickly switch between them.

.Steps

. Select the *Project* dropdown menu from the top navigation bar,
. Select the current project name to open the *Project Selection* menu and a list of available projects appears.
. Use the *Search Projects* bar to quickly find the project you want to switch to.
. Select the checkbox next to the name of the project you want to switch to.
. Select *Switch* to load the selected project.