---
sidebar: sidebar
permalink: prepare-install-using-aws.html
keywords: 
summary: 
---
= Prepare to install NDM using AWS
:icons: font
:imagesdir: ./media/

[.lead]
Use AWS to install NetApp Data Migrator (NDM).

.About this task

NDM has two main components that you need to install:

* The *control plane*, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

* *Workers* are virtual machines running on Linux, which supports the NFS protocol, or Windows, which supports the SMB protocol. You can install multiple workers based on your requirements:

** For shared message block (SMB) migration, use the Windows Worker Installer on a Windows VM.
** For NFS migration, use the Linux Worker.

.Steps

. To install the NDM control pane and worker, you must have the following prerequisites:
+
* An active AWS account with the required permissions
* A selected AWS region for deployment
* An S3 bucket for storing VHDs (if using VHD import)
* AWS command line interface (CLI) installed and configured
* Sufficient EC2 quota and storage

. Choose one of the following options:
+
[cols="1,2", options="header"]
|===
|If you... |Go to...
|Don't have the AWS CLI
| link:install-aws-cli.html[Install AWS CLI and manage assets for NDM]
| Have the AWS CLI installed
|link:create-aws-control-plane-worker-vm.html[Create the control plane and worker VMs]
|===
