---
sidebar: sidebar
permalink: prepare-install-using-aws.html
keywords: 
summary: 
---
= Prepare to install NDM using AWS
:icons: font
:imagesdir: ./media/

[.lead]
Use AWS to install NetApp Data Migrator (NDM).

.About this task

NDM has two main components that you need to install:

* The *control plane*, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

* *Workers* are virtual machines running on Linux, which supports the NFS protocol, or Windows, which supports the SMB protocol. You can install multiple workers based on your requirements:

** For shared message block (SMB) migration, use the Windows Worker Installer on a Windows VM.
** For NFS migration, use the Linux Worker.

.Steps

. To install the NDM control pane and worker, you must have the following prerequisites:
+
* An active AWS account with the required permissions
* A selected AWS region for deployment
* An S3 bucket for storing VHDs (if using VHD import)
* AWS command line interface (CLI) installed and configured
* Sufficient EC2 quota and storage

. Choose one of the following options:
+
[cols="1,2", options="header"]
|===
|If you... | You need to...
|Don't have the NDM assets
| Contact the NetApp NDM team at `ndm-support@netapp.com` to request the AWS Amazon Machine Image (AMI). Include the Account ID in the email or share with your NetApp contact so that images are shared to that account ID. After NetApp shares the AMI, it is visible in your AWS account under *EC2* > *AMIs* > *Private images*, and you can locate it using the AMI IDs provided.
| Have the AWS CLI and NDM assets installed
|Go to link:create-aws-control-plane-worker-vm.html[Create the control plane and worker VMs]
|===
