---
sidebar: sidebar
permalink: prepare-install-using-azure.html
keywords: azure installation, prerequisites, control plane, worker vm, azure cli
summary: "Prepare to install the NDM control plane and worker VMs by using Azure."
---
= Prepare for NDM installation using Azure
:icons: font
:imagesdir: ./media/

[.lead]
Use Azure to install NetApp Data Migrator (NDM).

.About this task

NDM has two main components that you need to install:

* The *control plane*, which is always deployed on a Linux virtual machine (VM), serves as the central location for managing all migration jobs and should be created first.

* *Workers* are virtual machines running on Linux or Windows. Linux supports the NFS protocol and Windows supports the SMB protocol. You can install multiple workers based on your requirements:

** For shared message block (SMB) migration, use the Windows Worker Installer on a Windows VM.
** For NFS migration, use the Linux Worker.

.Steps

. To install the NDM control pane and worker, you must have the following prerequisites:
+
* An active Azure subscription
* A Resource group set up in your desired region
* Sufficient disk space for data storage and VM deployment
* Azure command line interface (CLI) installed
. Verify that the ports for the control plane and workers are enabled:
+
include::./_include/configure-ports.adoc[]

. Choose one of the following options:
+
[cols="1,2", options="header"]
|===
|If you... |Go to...
|Don't have the Azure CLI
| link:install-azure-cli.html[Install Azure CLI and manage assets for NDM]
| Have the Azure CLI installed
|link:create-azure-control-plane-worker-vm.html[Create the control plane and worker VMs]
|===

// 2025 DEC 1, OTHERDOC-168