settings:
  name: NetApp Data Migrator
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
  - title: NetApp Data Migrator (NDM) docs
    url: /index.html
  - title: Release notes 
    entries:
    - title: What is NDM?
      url: /overview.html
    - title: Support matrix for NDM
      url: /support-matrix.html
    - title: Usage limits of NDM
      url: /usage-limitations.html
    - title: Known issues for NDM
      url: /known-issues.html
  - title: Get started
    entries: 
    - title: Learn about NDM
      url: /learn-about.html
    - title: Quick start 
      url: /quick-start.html
  - title: Install and setup
    entries:
    - title: Install NDM
      entries:
      - title: Learn about the install options
        url: /install-options.html
      - title: AWS
        entries:
        - title: Prepare for installation
          url: /prepare-install-using-aws.html
        - title: Install AWS CLI and manage assets 
          url: /install-aws-cli.html
        - title: Create the control plane and worker VMs
          url: /create-aws-control-plane-worker-vm.html
      - title: Azure
        entries:
        - title: Prepare for installation
          url: /prepare-install-using-azure.html
        - title: Install Azure CLI and manage assets 
          url: /install-azure-cli.html
        - title: Create the control plane and worker VMs
          url: /create-azure-control-plane-worker-vm.html
      - title: Google Cloud
        url: /install-on-google-cloud.html
      - title: OVA
        url: /install-using-ova.html
    - title: Configure NDM
      url: /configure-ndm.html
  - title: Use NDM
    entries: 
    - title: Create and manage projects
      url: /manage-projects.html
    - title: Manage users
      entries: 
      - title: Add and manage users
        url: /manage-users.html
      - title: Manage access control
        url: /access-control.html
    - title: Add and manage file servers
      url: /manage-file-servers.html
    - title: Configure real-time notifications
      url: /configure-notifications.html
    - title: Manage migration options
      entries:
      - title: Plan data migration
        url: /configure-bulk-discover.html
      - title: Configure Bulk Migrate
        url: /configure-bulk-migrate.html
      - title: Configure Bulk Cutover
        url: /configure-bulk-cutover.html
    - title: Manage jobs and job runs
      url: /manage-jobs.html
    - title: Generate support bundle
      url: /generate-support-bundle.html
  - title: Upgrade NDM
    url: /upgrade.html
  - title: FAQ
    url: /faq.html
  - title: Get help
    entries:
    - title: Troubleshoot
      url: /troubleshoot.html
  - title: Legal notices
    url: /legal-notices.html
