---
sidebar: sidebar
permalink: register-for-account.html
keywords: netapp, data, migrator, support, register, account
summary: "Create a NetApp account and complete the registration process to access NetApp Support."
---
= Register for a NetApp Data Migrator account
:icons: font
:imagesdir: ./media/

[.lead]
If you are a new NetApp customer, you need to create a NetApp account and complete the registration process to access NetApp Support. 

NOTE: It can take up to one business day for your new NetApp Support Site account to be upgraded from *Guest access* to *Full access*.

.Steps

. Register for an account on the link:https://mysupport.netapp.com/site/user/registration[NetApp Support Site^] using your business email.
. Select *Submit*.
. Authenticate the registration initiation by entering the onetime password sent to your email. 
. On the registration completion page, provide the required details: 
+
.. For User Access Level, select *NetApp Customer/End User*.
.. In the Serial Number field, enter `NDMNSSREG`.

. Select *Submit*. A confirmation window appears indicating that the user registration has been submitted successfully. 

If you encounter any issues during registration or want to check the status of your registration, link:https://mysupport.netapp.com/site/help[open a support ticket^].

.What's next?
After learning about registering for an account, you can link:deploy-control-plane-and-linux-workers.html[deploy the control plane and Linux worker VMs].
 

// 2026 APRIL 15, GA release