---
sidebar: sidebar
permalink: contact-support.html
keywords: support matrix, nfs, smb, file servers, protocol versions
summary: "Learn about NetApp Data Migrator support for features, file servers, and protocols."
---
= Get support for NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
If you are a new NetApp customer, to create a NetApp account complete the registration process to access NetApp Support. 

== Step 1: Register for an account 

Complete the NetApp account registration. It can take up to one business day for your new NetApp Support Site account to be upgraded from *Guest access* to *Full access*.

.Steps

. Register for an account on the link:https://mysupport.netapp.com/site/user/registration[NetApp Support Site^] using your business email.
. Select *Submit*.
. Authenticate the registration initiation by entering the onetime password sent to your email. 
. On the registration completion page, provide the required details: 
+
.. For User Access Level, select *NetApp Customer/End User*.
.. In the Serial Number field, enter `NDMNSSREG`.

. Select *Submit*. A confirmation window appears indicating that the user registration has been submitted successfully. 

If you encounter any issues during registration or want to check the status of your registration, link:https://mysupport.netapp.com/site/help[open a support ticket].

== Step 2: Install NetApp Data Migrator

Learn about link:learn-about-install.html[installing NetApp Data Migrator].
 
== Step 3: Register your NetApp Data Migrator product 

Register your NetApp Data Migrator product to enable the software.

.Steps
. Select *Help (?)* > *About* > *Serial Number*
. In the *About NDM* dialog box, record the NDM Instance ID. 
+
This is a 20-digit number, starting with 975.

. Go to the link:https://register.netapp.com[NetApp support site registration page^].
. Select *I am not a registered NetApp Customer*. 
. Fill in the required product registration details: 
+
.. Leave the *NetApp Reference SN* field blank 
.. From the Product Line dropdown, select *NDM*. 
.. From the Billing Provider dropdown, select *Azure NetApp Files*.
.. Enter the 20-digit NDM Instance ID in the *NDM Serial #* field.
.. Complete the remaining required fields, then select *Submit*. 
. After submission, you receive a registration confirmation email. Follow the instructions in the email to confirm the registration.