---
sidebar: sidebar
permalink: upgrade.html
keywords: 
summary: 
---
= Upgrade features in NDM
:icons: font
:imagesdir: ./media/

[.lead]
Follow these instructions to upgrade a control plane, Linux worker, or Windows worker in NetApp Data Migrator (NDM). 

.Before you begin

Stop all job runs and make all jobs inactive. Upgrade logs appear in the unzipped folder with the following file name format:

----
upgrade_<timestamp>.log. 
----

If you encounter issues, contact NetApp support at ng-ndm-support@netapp.com and attach the upgrade logs to your communication.


== Upgrade the control plane

.Steps

. Copy the upgrade bundle:
+
* Transfer the upgrade zip file to the control plane machine using `scp`:
+
[source,cli]
----
scp -P 2226 ~/2025.08.19-preview.zip ubuntu@localhost:/tmp
----
. SSH to the control plane and switch user: 
+
* Connect to the control plane machine and switch to the "datamigrator" user:
+
[source,cli]
----
$ sudo su - datamigrator
----
. Install, unzip, and extract the bundle:
+
.. Navigate to the /tmp directory, install unzip if necessary, and extract the upgrade package:
+
[source,cli]
----
$ cd /tmp 
$ sudo apt install unzip 
$ unzip 2025.08.19-preview.zip
----

.. Verify the extracted file:
+
After unzipping the upgrade package, you should see the following files in the extracted folder:
+
* A checksum file (for example, checksums.sha256)
* A Docker image tar file (for example, datamigrator-2025.08.23-main.tar)
* A Helm chart archive (for example, datamigrator-2025.08.23-main.tgz)
* The upgrade script (upgrade.sh). You can verify the contents of the directory by running the following command:
+
[source,cli]
----
$ cd 2025.08.19-preview 
$ ls -lart 
total 6962656 
-rw-r--r-- 1 datamigrator datamigrator 7129717248 Aug 23 11:16 datamigrator-2025.08.23-main.tar 
-rwxr-xr-x 1 datamigrator datamigrator 7392 Aug 23 11:16 upgrade.sh 
-rw-r--r-- 1 datamigrator datamigrator 6046 Aug 23 11:16 datamigrator-2025.08.23-main.tgz 
-rw-r--r-- 1 datamigrator datamigrator 275 Aug 23 11:17 checksums.sha256
----
. Prepare and run the upgrade script:

.. Make the upgrade script executable. 
.. Run the  upgrade script to provide the paths to the checksum file, Docker tar file, and Helm chart archive:
+
[source,cli]
----
$ sudo chmod +x upgrade.sh
$ ./upgrade.sh <path-to-check-sum-file> <path-to-docker-tar-file> <path-to-helm-tgz-file>
----
+
You should see an output similar to the following example:
+
----
./upgrade.sh checksums.sha256 datamigrator-2025.08.19-preview.tar datamigrator-2025.08.19-preview.tgz
----
 

. Resume the jobs.

. After the upgrade completes, you need to:
+
.. Create a new job run for any stopped jobs, because these cannot be restarted.
.. Reactivate any inactive jobs to ensure that they run as scheduled.

== Upgrade a Linux worker

.Steps
. Create a new VM with the image provided for upgrade. 
. Perform the following steps for previously created jobs:
.. Detach the old worker from both the source and destination file servers.
.. Attach the new worker to both the source and destination file servers.
.. Create a new migration job to find and migrate differences between the source and destination data.

== Upgrade a Windows worker

.Steps
. Uninstall the existing application, then install the new executable on the Windows machine.
. Perform the following steps for previously created jobs:
.. Detach the old worker from both the source and destination file servers.
.. Attach the new worker to both the source and destination file servers.
.. Create a new migration job to find and migrate differences between the source and destination data.



 