---
sidebar: sidebar
permalink: upgrade.html
keywords: 
summary: 
---
= Upgrade features in NDM
:icons: font
:imagesdir: ./media/

[.lead]
Upgrade a control plane, Linux worker, or Windows worker in NetApp Data Migrator (NDM). 

.Before you begin

* Stop all job runs and make all jobs inactive. 
* Download the upgrade bundle (tar.gz file) from the NetApp Support Site and save it in your local directory.
* Verify that the workers that in use are online. Workers that that are offline during an upgrade are not upgraded.
* If you encounter issues, contact NetApp support at ng-ndm-support@netapp.com and attach the upgrade logs to your communication.  

== Step 1: Upload the upgrade bundle
After you upload the upgrade bundle, you can start the upgrade process for the control plane and worker.

.Steps

. Log in to the NDM UI, then navigate to the home page.
. Select the help icon in the top right corner.
. Select the *Upgrade* tab.
. Select *Select file*, then select the upgrade bundle tar.gz file. 
. Select *Upload* after selecting the file.
+
Wait for the message to appear that confirms that the upload and validation are complete.
. Optionally, start the process again by selecting *Start Over* to upload a different file.

== Step 2: Upgrade the control plane and worker

Upgrade the control plane followed by the Linux worker or Windows worker.

.Steps
. Select *Upgrade*. The system starts upgrading the control plane. This takes approximately five to ten minutes.
+
During the upgrade, the UI might become temporarily unavailable because the application is restarting with the new version. Log back into the UI when it becomes accessible again. 

. After the upgrade completes, return to the *Upgrade* page. 
. Verify that the upgrade status is *Success*.
. After a successful control plane upgrade, the worker upgrade starts automatically for all online workers. 
+
The online workers automatically install and restart with the new version. 
Offline workers are not be upgraded. 
. If a worker upgrade does not start automatically, use SSH to connect to the worker and start the upgrade manually:
+
[role="tabbed-block"]
====
.Linux worker
--
[source,cli]
----
sudo /opt/datamigrator/staging/<version>/upgrade.sh <version>
----
--
.Windows worker
--
[source,cli]
----
ExecutionPolicy Bypass -File C:\datamigrator\staging\<version>\upgrade.ps1 -Version <version>
----
--
====
. If the upgrade fails:

* The system automatically rolls back to the previous version. 
* The UI shows the upgrade status as *Failed*.

+
<<view-logs,Review the Ansible logs>> on the virtual machine for details. Contact NetApp support at ng-ndm-support@netapp.com and attach the Ansible logs to your communication.

[[view-logs]]
== Step 3: View logs 
If you encounter issues during the upgrade, view the logs for details.

.Steps

. SSH to the control plane VM and run the following command to view logs:
+
[source,cli]
----
tail -f /upgrade/upgrade-<version>.log 
----
. SSH to the Linux worker or Windows worker VM and view the logs by using the following path:
+
[source,cli]
----
/opt/datamigrator/upgrade.log
----

// 2026 FEB 25, Preview + 3 release