---
sidebar: sidebar
permalink: whats-new.html
keywords: netapp, data, migrator, whats new, release, notes
summary: "Learn what's new in this doc site."
---
= What's new in NetApp Data Migrator
:icons: font
:imagesdir: ./media/

[.lead]
Learn about what's new in NetApp Data Migrator.

== 12 June 2026

NetApp Data Migrator 2026.06.0 improves the accuracy, reliability, scalability, and security for data migrations:

* Improves the accuracy of incremental migrations and metadata preservation for SMB with the inclusion of configurable permission inheritance modes and improved metadata synchronization.
* Includes performance and stability improvements across discovery, migration, and permission-stamping workflows for NFS and SMB.

== 22 April 2026

NetApp Data Migrator 2026.04.0 offers a new solution for migrating data files. You can use NetApp Data Migrator to migrate data from on-premises or third-party storage systems to NetApp cloud storage services. NetApp Data Migrator supports the NFS and SMB file transfer protocols.

link:learn-about-data-migrator.html[Learn more about NetApp Data Migrator]
